/* SPDX-License-Identifier: GPL-2.0-only */

#ifndef MAINBOARD_GPIO_H
#define MAINBOARD_GPIO_H

#ifndef __ACPI__

#include <soc/gpe.h>
#include <soc/gpio.h>

/* Pad configuration in romstage. */
static const struct pad_config early_gpio_table[] = {
		// UART2_RXD
		PAD_CFG_NF(GPP_C20, UP_20K, DEEP, NF1),
		// UART2_TXD
		PAD_CFG_NF(GPP_C21, UP_20K, DEEP, NF1),
};

/* Pad configuration in ramstage. */
static const struct pad_config gpio_table[] = {
		// PM_BATLOW#
		PAD_CFG_NF(GPD0, UP_20K, PWROK, NF1),
		// AC_PRESENT
		PAD_CFG_NF(GPD1, NATIVE, PWROK, NF1),
		// NC
		PAD_CFG_GPI(GPD2, NONE, PWROK),
		// PWR_BTN#
		PAD_CFG_NF(GPD3, UP_20K, PWROK, NF1),
		// SUSB#_PCH
		PAD_CFG_NF(GPD4, NONE, PWROK, NF1),
		// SUSC#_PCH
		PAD_CFG_NF(GPD5, NONE, PWROK, NF1),
		// SLP_A# - test point
		PAD_CFG_NF(GPD6, NONE, DEEP, NF1),
		// GPD7_REST
		PAD_CFG_TERM_GPO(GPD7, 1, NONE, PWROK),
		// SUS_CLK
		PAD_CFG_NF(GPD8, NONE, PWROK, NF1),
		// GPD9_RTD3
		PAD_CFG_TERM_GPO(GPD9, 0, NONE, PWROK),
		// SLP_S5# - test point
		PAD_CFG_NF(GPD10, UP_20K, DEEP, NF1),
		// NC
		PAD_CFG_GPI(GPD11, UP_20K, DEEP),
		// ESPI_IO_0
		PAD_CFG_NF(GPP_A0, UP_20K, DEEP, NF1),
		// ESPI_IO_1
		PAD_CFG_NF(GPP_A1, UP_20K, DEEP, NF1),
		// ESPI_IO_2
		PAD_CFG_NF(GPP_A2, UP_20K, DEEP, NF1),
		// ESPI_IO_3
		PAD_CFG_NF(GPP_A3, UP_20K, DEEP, NF1),
		// ESPI_CS_N
		PAD_CFG_NF(GPP_A4, UP_20K, DEEP, NF1),
		// ESPI_CLK
		PAD_CFG_NF(GPP_A5, DN_20K, DEEP, NF1),
		// ESPI_RESET_N
		PAD_CFG_NF(GPP_A6, NONE, DEEP, NF1),
		// NC
		PAD_NC(GPP_A7, NONE),
		// CNVI_RST#
		PAD_CFG_NF(GPP_A8, NONE, DEEP, NF2),
		// CNVI_CLKREQ
		PAD_CFG_NF(GPP_A9, NONE, DEEP, NF3),
		// GPPC_DMIC_DATA
		PAD_NC(GPP_A10, NONE),
		// NC
		PAD_NC(GPP_A11, NONE),
		// SATAGP1
		PAD_CFG_NF(GPP_A12, NONE, DEEP, NF1),
		// PCH_BT_EN
		PAD_CFG_TERM_GPO(GPP_A13, 1, NONE, PLTRST),
		// GPPC_DMIC_CLK
		PAD_NC(GPP_A14, NONE),
		// USB_OC2#
		PAD_NC(GPP_A15, NONE),
		// USB_OC3#
		PAD_NC(GPP_A16, NONE),
		// NC
		PAD_NC(GPP_A17, NONE),
		// HDMI_HPD
		PAD_CFG_NF(GPP_A18, NONE, DEEP, NF1),
		// NC
		PAD_NC(GPP_A19, NONE),
		// NC
		PAD_NC(GPP_A20, NONE),
		// NC
		PAD_NC(GPP_A21, NONE),
		// NC
		PAD_NC(GPP_A22, NONE),
		// TC_RETIMER_FORCE_PWR
		PAD_CFG_TERM_GPO(GPP_A23, 0, NONE, PLTRST),
		// VCCIN_AUX_VID0
		PAD_CFG_NF(GPP_B0, NONE, DEEP, NF1),
		// VCCIN_AUX_VID1
		PAD_CFG_NF(GPP_B1, NONE, DEEP, NF1),
		// VRALERT#
		PAD_CFG_GPI(GPP_B2, UP_20K, DEEP),
		// GPP_B3 - touchpad interrupt
		PAD_CFG_GPI_INT(GPP_B3, NONE, PLTRST, LEVEL),
		// NC
		PAD_NC(GPP_B4, NONE),
		// PCH_FLASH_I2C_SDA - test point
		PAD_NC(GPP_B5, NONE),
		// PCH_FLASH_I2C_SCL - test point
		PAD_NC(GPP_B6, NONE),
		// NC
		PAD_NC(GPP_B7, NONE),
		// NC
		PAD_NC(GPP_B8, NONE),
		// NC
		PAD_NC(GPP_B9, NONE),
		// NC
		PAD_NC(GPP_B10, NONE),
		// TBTA_I2C_INT
		PAD_CFG_NF(GPP_B11, NONE, PWROK, NF1),
		// SLP_S0#
		PAD_CFG_NF(GPP_B12, NONE, DEEP, NF1),
		// PLT_RST#
		PAD_CFG_NF(GPP_B13, NONE, DEEP, NF1),
		// PCH_SPKR
		PAD_CFG_TERM_GPO(GPP_B14, 0, NONE, DEEP),
		// NC
		PAD_NC(GPP_B15, NONE),
		// PCH_GPP_B16 - test point
		PAD_NC(GPP_B16, NONE),
		// NC
		PAD_NC(GPP_B17, NONE),
		// PCH_GPP_B18 - No reboot strap
		PAD_NC(GPP_B18, NONE),
		// NC
		PAD_NC(GPP_B19, NONE),
		// NC
		PAD_NC(GPP_B20, NONE),
		// NC
		PAD_NC(GPP_B21, NONE),
		// NC
		PAD_NC(GPP_B22, NONE),
		// GPP_B23
		PAD_CFG_TERM_GPO(GPP_B23, 0, NONE, DEEP),
		// SMB_CLK
		PAD_CFG_NF(GPP_C0, NONE, DEEP, NF1),
		// SMB_DATA
		PAD_CFG_NF(GPP_C1, NONE, DEEP, NF1),
		// PCH_GPP_C2 - ME TLS strap
		PAD_CFG_TERM_GPO(GPP_C2, 1, NONE, DEEP),
		// SML0_CLK
		PAD_CFG_NF(GPP_C3, NONE, DEEP, NF1),
		// SML0_DATA
		PAD_CFG_NF(GPP_C4, NONE, DEEP, NF1),
		// PCH_GPP_C5 - boot strap bit 0
		PAD_NC(GPP_C5, NONE),
		// TBT_I2C_SCL
		PAD_CFG_NF(GPP_C6, NONE, PWROK, NF1),
		// TBT_I2C_SDA
		PAD_CFG_NF(GPP_C7, NONE, PWROK, NF1),
		// NC
		PAD_NC(GPP_C8, NONE),
		// TPM_PIRQ#
		_PAD_CFG_STRUCT(GPP_C9, 0x40100100, 0x3000),
		// NC
		PAD_NC(GPP_C10, NONE),
		// NC
		PAD_NC(GPP_C11, NONE),
		// NC
		PAD_NC(GPP_C12, NONE),
		// SSD1_PWR_DN#
		PAD_CFG_TERM_GPO(GPP_C13, 1, NONE, PLTRST),
		// NC
		PAD_NC(GPP_C14, DN_20K),
		// NC
		PAD_NC(GPP_C15, NONE),
		// T_SDA
		PAD_CFG_NF(GPP_C16, NONE, DEEP, NF1),
		// T_SCL
		PAD_CFG_NF(GPP_C17, NONE, DEEP, NF1),
		// PCH_I2C_SDA
		PAD_CFG_NF(GPP_C18, NONE, DEEP, NF1),
		// PCH_I2C_SCL
		PAD_CFG_NF(GPP_C19, NONE, DEEP, NF1),
		// UART2_RXD
		PAD_CFG_NF(GPP_C20, UP_20K, DEEP, NF1),
		// UART2_TXD
		PAD_CFG_NF(GPP_C21, UP_20K, DEEP, NF1),
		// GPP_C12_RTD3
		PAD_CFG_TERM_GPO(GPP_C22, 1, NONE, PLTRST),
		// PCH_GPP_C23
		_PAD_CFG_STRUCT(GPP_C23, 0x40880100, 0x0000),
		// SB_BLON
		PAD_CFG_TERM_GPO(GPP_D0, 1, NONE, DEEP),
		// DDR_TYPE_D1
		PAD_CFG_GPI(GPP_D1, NONE, DEEP),
		// LEDKB_DET#
		PAD_CFG_GPI(GPP_D2, DN_20K, DEEP),
		// BOARD_ID
		PAD_CFG_GPI(GPP_D3, DN_20K, DEEP),
		// NC
		PAD_NC(GPP_D4, NONE),
		// SSD1_CLKREQ#
		PAD_CFG_NF(GPP_D5, NONE, DEEP, NF1),
		// WLAN_CLKREQ#
		PAD_CFG_NF(GPP_D6, NONE, DEEP, NF1),
		// CARD_CLKREQ#
		PAD_CFG_NF(GPP_D7, NONE, DEEP, NF1),
		// SSD2_CLKREQ#
		PAD_CFG_NF(GPP_D8, NONE, DEEP, NF1),
		// GPP_D13_RTD3 - named incorrectly in schematic
		PAD_CFG_TERM_GPO(GPP_D9, 1, NONE, PLTRST),
		// GPP_D10 - I2C / TBT_LSX2 pin voltage (L=1.8V, H=3.3V)
		PAD_NC(GPP_D10, NONE),
		// NC
		PAD_CFG_GPI(GPP_D11, DN_20K, DEEP),
		// GPP_D12 - I2C / TBT_LSX3 pin voltage (L=1.8V, H=3.3V)
		PAD_NC(GPP_D12, NONE),
		// NC
		PAD_NC(GPP_D13, NONE),
		// SSD2_PWR_DN#
		PAD_CFG_TERM_GPO(GPP_D14, 1, NONE, PLTRST),
		// NC
		PAD_NC(GPP_D15, NONE),
		// NC
		PAD_NC(GPP_D16, NONE),
		// DDR_TYPE_D17
		PAD_CFG_GPI(GPP_D17, NONE, DEEP),
		// DDR_TYPE_D18
		PAD_CFG_GPI(GPP_D18, NONE, DEEP),
		// NC
		PAD_NC(GPP_D19, NONE),
		// NC
		PAD_NC(GPP_E0, NONE),
		// ROM_I2C_EN
		PAD_CFG_TERM_GPO(GPP_E1, 0, NONE, PLTRST),
		// NC
		PAD_NC(GPP_E2, NONE),
		// SB_KBCRST#
		PAD_CFG_GPI(GPP_E3, DN_20K, DEEP),
		// DEVSLP0
		PAD_NC(GPP_E4, NONE),
		// DEVSLP1
		PAD_CFG_NF(GPP_E5, NONE, DEEP, NF1),
		// PCH_GPP_E6 - reserved strap
		PAD_NC(GPP_E6, NONE),
		// NC
		PAD_NC(GPP_E7, NONE),
		// NC
		PAD_NC(GPP_E8, NONE),
		// USB_OC0#
		PAD_NC(GPP_E9, NONE),
		// PCH_GPP_E10 - THC0_SPI1 chip select
		PAD_NC(GPP_E10, NONE),
		// PCH_GPP_E11 - THC0_SPI1 clock
		PAD_NC(GPP_E11, NONE),
		// NC
		PAD_NC(GPP_E12, NONE),
		// NC
		PAD_NC(GPP_E13, NONE),
		// EDP_HPD
		PAD_CFG_NF(GPP_E14, NONE, DEEP, NF1),
		// SCI#
		PAD_CFG_GPI(GPP_E15, DN_20K, DEEP),
		// SMI#
		_PAD_CFG_STRUCT(GPP_E16, 0x82840100, 0x0000),
		// NC
		PAD_NC(GPP_E17, NONE),
		// TBT_LSX0_TXD - programmed by FSP, see Intel document 617016
		PAD_NC(GPP_E18, NONE),
		// TBT_LSX0_RXD - programmed by FSP, see Intel document 617016
		PAD_NC(GPP_E19, NONE),
		// SWI#
		_PAD_CFG_STRUCT(GPP_E20, 0x40880100, 0x0000),
		// GPP_E21 - DDP2 I2C / TBT_LSX1 pin voltage (L=1.8V, H=3.3V)
		PAD_NC(GPP_E21, NONE),
		// NC
		PAD_NC(GPP_E22, NONE),
		// NC
		PAD_NC(GPP_E23, NONE),
		// CNVI_BRI_DT
		PAD_CFG_NF(GPP_F0, NONE, DEEP, NF1),
		// CNVI_BRI_RSP
		PAD_CFG_NF(GPP_F1, UP_20K, DEEP, NF1),
		// CNVI_RGI_DT
		PAD_CFG_NF(GPP_F2, NONE, DEEP, NF1),
		// CNVI_RGI_RSP
		PAD_CFG_NF(GPP_F3, UP_20K, DEEP, NF1),
		// NC
		PAD_NC(GPP_F4, NONE),
		// NC
		PAD_NC(GPP_F5, NONE),
		// CNVI_GNSS_PA_BLANKING
		PAD_NC(GPP_F6, NONE),
		// GPP_F7 - reserved strap
		PAD_NC(GPP_F7, NONE),
		// NC
		PAD_NC(GPP_F8, NONE),
		// NC
		PAD_NC(GPP_F9, NONE),
		// GPP_F10 - reserved strap
		PAD_NC(GPP_F10, NONE),
		// NC
		PAD_NC(GPP_F11, NONE),
		// NC
		PAD_NC(GPP_F12, NONE),
		// NC
		PAD_NC(GPP_F13, NONE),
		// NC
		PAD_NC(GPP_F14, NONE),
		// NC
		PAD_NC(GPP_F15, NONE),
		// NC
		PAD_NC(GPP_F16, NONE),
		// TPM_DET#
		PAD_CFG_GPI(GPP_F17, NONE, PLTRST),
		// NC
		PAD_NC(GPP_F18, NONE),
		// NC
		PAD_NC(GPP_F19, NONE),
		// EXT_PWR_GATE#
		PAD_NC(GPP_F20, NONE),
		// EXT_PWR_GATE2#
		PAD_CFG_GPI(GPP_F21, DN_20K, DEEP),
		// VNN_CTRL
		PAD_NC(GPP_F22, NONE),
		// V1P05_CTRL
		PAD_NC(GPP_F23, NONE),
		// GPP_H0 - boot strap bit 1
		PAD_NC(GPP_H0, DN_20K),
		// GPP_H1 - boot strap bit 2
		PAD_NC(GPP_H1, DN_20K),
		// GPP_H2 - boot strap bit 3
		PAD_NC(GPP_H2, DN_20K),
		// NC
		PAD_CFG_GPI(GPP_H3, DN_20K, DEEP),
		// NC
		PAD_NC(GPP_H4, NONE),
		// NC
		PAD_NC(GPP_H5, NONE),
		// test point
		PAD_CFG_GPI(GPP_H6, NONE, DEEP),
		// test point
		PAD_NC(GPP_H7, NONE),
		// CNVI_MFUART2_RXD
		PAD_CFG_GPI(GPP_H8, DN_20K, DEEP),
		// CNVI_MFUART2_TXD
		PAD_CFG_GPI(GPP_H9, DN_20K, DEEP),
		// NC
		PAD_NC(GPP_H10, NONE),
		// NC
		PAD_NC(GPP_H11, NONE),
		// NC
		PAD_NC(GPP_H12, NONE),
		// NC
		PAD_NC(GPP_H13, NONE),
		// G_INT1
		PAD_NC(GPP_H14, NONE),
		// NC
		PAD_NC(GPP_H15, NONE),
		// HDMI_CTRLCLK
		PAD_CFG_NF(GPP_H16, NONE, DEEP, NF1),
		// HDMI_CTRLDATA
		PAD_CFG_NF(GPP_H17, NONE, DEEP, NF1),
		// CPU_C10_GATE#
		PAD_CFG_NF(GPP_H18, NONE, DEEP, NF1),
		// CNVI_WAKE#
		PAD_NC(GPP_H19, NONE),
		// PM_CLKRUN#
		PAD_NC(GPP_H20, NONE),
		// NC
		PAD_NC(GPP_H21, NONE),
		// NC
		PAD_NC(GPP_H22, NONE),
		// NC
		PAD_NC(GPP_H23, NONE),
		// HDA_BITCLK
		PAD_CFG_NF(GPP_R0, NONE, DEEP, NF1),
		// HDA_SYNC
		PAD_CFG_NF(GPP_R1, NATIVE, DEEP, NF1),
		// HDA_SDOUT
		PAD_CFG_NF(GPP_R2, NATIVE, DEEP, NF1),
		// HDA_SDIN0
		PAD_CFG_NF(GPP_R3, NATIVE, DEEP, NF1),
		// AZ_RST#_R
		PAD_CFG_NF(GPP_R4, NONE, DEEP, NF1),
		// NC
		PAD_NC(GPP_R5, NONE),
		// NC
		PAD_NC(GPP_R6, NONE),
		// NC
		PAD_NC(GPP_R7, NONE),
		// NC
		PAD_NC(GPP_S0, NONE),
		// NC
		PAD_NC(GPP_S1, NONE),
		// NC
		PAD_NC(GPP_S2, NONE),
		// NC
		PAD_NC(GPP_S3, NONE),
		// NC
		PAD_NC(GPP_S4, NONE),
		// NC
		PAD_NC(GPP_S5, NONE),
		// NC
		PAD_CFG_GPI(GPP_S6, NONE, DEEP),
		// NC
		PAD_CFG_GPI(GPP_S7, NONE, DEEP),
		// NC
		PAD_NC(GPP_T2, NONE),
		// NC
		PAD_NC(GPP_T3, NONE),
		// NC
		PAD_NC(GPP_U4, NONE),
		// NC
		PAD_NC(GPP_U5, NONE),
};

#endif

#endif
