/* SPDX-License-Identifier: GPL-2.0-only */

#ifndef CFG_GPIO_H
#define CFG_GPIO_H

#include <soc/gpio.h>

#ifndef PAD_CFG_GPIO_BIDIRECT
#define PAD_CFG_GPIO_BIDIRECT(pad, val, pull, rst, trig, own)           \
	_PAD_CFG_STRUCT(pad,                                            \
		PAD_FUNC(GPIO) | PAD_RESET(rst) | PAD_TRIG(trig) |      \
		PAD_BUF(NO_DISABLE) | val,                              \
		PAD_PULL(pull) | PAD_CFG_OWN_GPIO(own))
#endif

/* Pad configuration was generated automatically using intelp2m utility */
static const struct pad_config gpio_table[] = {
	/* ------- GPIO Community 0 ------- */

	/* ------- GPIO Group GPP_I ------- */
	PAD_CFG_GPI_TRIG_OWN(GPP_I0, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_NF(GPP_I1, NONE, PLTRST, NF1),	/* DDSP_HPD1 */
	PAD_CFG_NF(GPP_I2, NONE, PLTRST, NF1),	/* DDSP_HPD2 */
	PAD_CFG_NF(GPP_I3, NONE, PLTRST, NF1),	/* DDSP_HPD3 */
	PAD_CFG_NF(GPP_I4, NONE, PLTRST, NF1),	/* DDSP_HPD4 */
	PAD_CFG_GPI_TRIG_OWN(GPP_I5, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_I6, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_I7, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_I8, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_I9, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_I10, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_NF(GPP_I11, NONE, DEEP, NF1),	/* USB_OC4# */
	PAD_CFG_NF(GPP_I12, NONE, DEEP, NF1),	/* USB_OC5# */
	PAD_CFG_NF(GPP_I13, NONE, DEEP, NF1),	/* USB_OC6# */
	PAD_CFG_NF(GPP_I14, NONE, DEEP, NF1),	/* USB_OC7# */
	PAD_CFG_GPI_TRIG_OWN(GPP_I15, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_I16, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_I17, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_I18, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_I19, NONE, RSMRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_I20, NONE, RSMRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_I21, NONE, RSMRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_I22, NONE, PLTRST, OFF, ACPI),	/* GPIO */

	/* ------- GPIO Group GPP_R ------- */
	PAD_CFG_NF(GPP_R0, NONE, DEEP, NF1),	/* HDA_BCLK */
	PAD_CFG_NF(GPP_R1, NONE, DEEP, NF1),	/* HDA_SYNC */
	PAD_CFG_NF(GPP_R2, NONE, DEEP, NF1),	/* HDA_SDO */
	PAD_CFG_NF(GPP_R3, NONE, DEEP, NF1),	/* HDA_SDI0 */
	PAD_CFG_NF(GPP_R4, NONE, DEEP, NF1),	/* HDA_RST# */
	PAD_CFG_GPI_TRIG_OWN(GPP_R5, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_R6, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_R7, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_R8, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_R9, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_R10, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_R11, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_NF(GPP_R12, NONE, PLTRST, NF2),	/* DDP3_CTRLCLK */
	PAD_CFG_NF(GPP_R13, NONE, PLTRST, NF2),	/* DDP3_CTRLDATA */
	PAD_CFG_GPI_TRIG_OWN(GPP_R14, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_R15, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_NF(GPP_R16, NONE, PLTRST, NF1),	/* DDP1_CTRLCLK */
	PAD_CFG_NF(GPP_R17, NONE, PLTRST, NF1),	/* DDP1_CTRLDATA */
	PAD_CFG_NF(GPP_R18, NONE, PLTRST, NF1),	/* DDP2_CTRLCLK */
	PAD_CFG_NF(GPP_R19, NONE, PLTRST, NF1),	/* DDP2_CTRLDATA */
	PAD_CFG_GPI_TRIG_OWN(GPP_R20, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_R21, NONE, PLTRST, OFF, ACPI),	/* GPIO */

	/* ------- GPIO Group GPP_J ------- */
	PAD_CFG_GPI_TRIG_OWN(GPP_J0, NONE, RSMRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_NF(GPP_J1, NONE, PLTRST, NF1),	/* CPU_C10_GATE# */
	PAD_CFG_NF(GPP_J2, NONE, DEEP, NF1),	/* CNV_BRI_DT */
	PAD_CFG_NF(GPP_J3, NONE, DEEP, NF1),	/* CNV_BRI_RSP */
	PAD_CFG_NF(GPP_J4, NONE, DEEP, NF1),	/* CNV_RGI_DT */
	PAD_CFG_NF(GPP_J5, NONE, DEEP, NF1),	/* CNV_RGI_RSP */
	PAD_CFG_GPI_TRIG_OWN(GPP_J6, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPO(GPP_J7, 0, PLTRST),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_J8, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_J9, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_J10, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_J11, NONE, PLTRST, OFF, ACPI),	/* GPIO */

	/* ------- GPIO Group vGPIO ------- */
	PAD_CFG_GPIO_BIDIRECT(VGPIO_0, 0, NONE, DEEP, LEVEL, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(VGPIO_4, NONE, DEEP, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPIO_BIDIRECT(VGPIO_5, 1, NONE, DEEP, LEVEL, ACPI),	/* GPIO */
	PAD_CFG_NF(VGPIO_6, NONE, DEEP, NF1),	/* VGPIO_6 */
	PAD_CFG_NF(VGPIO_7, NONE, DEEP, NF1),	/* VGPIO_7 */
	PAD_CFG_NF(VGPIO_8, NONE, DEEP, NF1),	/* VGPIO_8 */
	PAD_CFG_NF(VGPIO_9, NONE, DEEP, NF1),	/* VGPIO_9 */
	PAD_CFG_NF(VGPIO_10, NONE, DEEP, NF1),	/* VGPIO_10 */
	PAD_CFG_NF(VGPIO_11, NONE, DEEP, NF1),	/* VGPIO_11 */
	PAD_CFG_NF(VGPIO_12, NONE, DEEP, NF1),	/* VGPIO_12 */
	PAD_CFG_NF(VGPIO_13, NONE, DEEP, NF1),	/* VGPIO_13 */
	PAD_CFG_NF(VGPIO_18, NONE, DEEP, NF1),	/* VGPIO_18 */
	PAD_CFG_NF(VGPIO_19, NONE, DEEP, NF1),	/* VGPIO_19 */
	PAD_CFG_NF(VGPIO_20, NONE, DEEP, NF1),	/* VGPIO_20 */
	PAD_CFG_NF(VGPIO_21, NONE, DEEP, NF1),	/* VGPIO_21 */
	PAD_CFG_NF(VGPIO_22, NONE, DEEP, NF1),	/* VGPIO_22 */
	PAD_CFG_NF(VGPIO_23, NONE, DEEP, NF1),	/* VGPIO_23 */
	PAD_CFG_NF(VGPIO_24, NONE, DEEP, NF1),	/* VGPIO_24 */
	PAD_CFG_NF(VGPIO_25, NONE, DEEP, NF1),	/* VGPIO_25 */
	PAD_CFG_NF(VGPIO_30, NONE, DEEP, NF1),	/* VGPIO_30 */
	PAD_CFG_NF(VGPIO_31, NONE, DEEP, NF1),	/* VGPIO_31 */
	PAD_CFG_NF(VGPIO_32, NONE, DEEP, NF1),	/* VGPIO_32 */
	PAD_CFG_NF(VGPIO_33, NONE, DEEP, NF1),	/* VGPIO_33 */
	PAD_CFG_NF(VGPIO_34, NONE, DEEP, NF1),	/* VGPIO_34 */
	PAD_CFG_NF(VGPIO_35, NONE, DEEP, NF1),	/* VGPIO_35 */
	PAD_CFG_NF(VGPIO_36, NONE, DEEP, NF1),	/* VGPIO_36 */
	PAD_CFG_NF(VGPIO_37, NONE, DEEP, NF1),	/* VGPIO_37 */

	/* ------- GPIO Group vGPIO_0 ------- */
	PAD_CFG_NF(VGPIO_USB_0, NONE, DEEP, NF1),	/* VGPIO_USB_0 */
	PAD_CFG_NF(VGPIO_USB_1, NONE, DEEP, NF1),	/* VGPIO_USB_1 */
	PAD_CFG_NF(VGPIO_USB_2, NONE, DEEP, NF1),	/* VGPIO_USB_2 */
	PAD_CFG_NF(VGPIO_USB_3, NONE, DEEP, NF1),	/* VGPIO_USB_3 */
	PAD_CFG_NF(VGPIO_USB_8, NONE, DEEP, NF1),	/* VGPIO_USB_8 */
	PAD_CFG_NF(VGPIO_USB_9, NONE, DEEP, NF1),	/* VGPIO_USB_9 */
	PAD_CFG_NF(VGPIO_USB_10, NONE, DEEP, NF1),	/* VGPIO_USB_10 */
	PAD_CFG_NF(VGPIO_USB_11, NONE, DEEP, NF1),	/* VGPIO_USB_11 */

	/* ------- GPIO Community 1 ------- */

	/* ------- GPIO Group GPP_B ------- */
	PAD_CFG_GPI_TRIG_OWN(GPP_B0, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_B1, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_B2, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPO(GPP_B3, 1, PLTRST),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_B4, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_B5, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_B6, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_B7, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_B8, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_B9, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_B10, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_B11, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_B12, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_NF(GPP_B13, NONE, DEEP, NF1),	/* PLTRST# */
	PAD_CFG_NF(GPP_B14, DN_20K, DEEP, NF1),	/* SPKR */
	PAD_CFG_GPI_TRIG_OWN(GPP_B15, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_B16, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_B17, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_NF(GPP_B18, UP_20K, PLTRST, NF1),	/* PMCALERT# */
	PAD_CFG_GPI_TRIG_OWN(GPP_B19, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_B20, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_B21, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_B22, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_B23, NONE, PLTRST, OFF, ACPI),	/* GPIO */

	/* ------- GPIO Group GPP_G ------- */
	PAD_CFG_GPI_TRIG_OWN(GPP_G0, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPO(GPP_G1, 1, PLTRST),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_G2, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPO(GPP_G3, 0, PLTRST),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_G4, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_G5, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_G6, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_SCI(GPP_G7, NONE, PLTRST, EDGE_SINGLE, INVERT),	/* GPIO */

	/* ------- GPIO Group GPP_H ------- */
	PAD_CFG_GPI_TRIG_OWN(GPP_H0, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_H1, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_H2, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_H3, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_H4, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_NF(GPP_H5, NONE, DEEP, NF1),	/* SRCCLKREQ11# */
	PAD_CFG_GPI_TRIG_OWN(GPP_H6, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_H7, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_H8, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_H9, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_H10, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_H11, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_H12, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_H13, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_H14, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_H15, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_H16, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_H17, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_H18, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_H19, NONE, RSMRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_H20, NONE, RSMRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_H21, NONE, RSMRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_H22, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_H23, NONE, PLTRST, OFF, ACPI),	/* GPIO */

	/* ------- GPIO Community 2 ------- */

	/* ------- GPIO Group GPD ------- */
	PAD_CFG_GPI_TRIG_OWN(GPD0, NONE, PWROK, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPD1, NONE, PWROK, OFF, ACPI),	/* GPIO */
	PAD_CFG_NF(GPD2, NONE, PWROK, NF1),	/* LAN_WAKE# */
	PAD_CFG_NF(GPD3, NONE, PWROK, NF1),	/* PWRBTN# */
	PAD_CFG_NF(GPD4, NONE, PWROK, NF1),	/* SLP_S3# */
	PAD_CFG_NF(GPD5, NONE, PWROK, NF1),	/* SLP_S4# */
	PAD_CFG_GPI_TRIG_OWN(GPD6, NONE, PWROK, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPD7, NONE, PWROK, OFF, ACPI),	/* GPIO */
	PAD_CFG_NF(GPD8, NONE, PWROK, NF1),	/* SUSCLK */
	PAD_CFG_GPI_TRIG_OWN(GPD9, NONE, PWROK, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPO(GPD10, 0, PWROK),	/* GPIO */
	PAD_CFG_GPO(GPD11, 0, PWROK),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPD12, NONE, PWROK, OFF, ACPI),	/* GPIO */

	/* ------- GPIO Community 3 ------- */

	/* ------- GPIO Group SPI ------- */

	/* ------- GPIO Group GPP_A ------- */
	PAD_CFG_NF(GPP_A0, UP_20K, DEEP, NF1),	/* ESPI_IO0 */
	PAD_CFG_NF(GPP_A1, UP_20K, DEEP, NF1),	/* ESPI_IO1 */
	PAD_CFG_NF(GPP_A2, UP_20K, DEEP, NF1),	/* ESPI_IO2 */
	PAD_CFG_NF(GPP_A3, UP_20K, DEEP, NF1),	/* ESPI_IO3 */
	PAD_CFG_NF(GPP_A4, UP_20K, DEEP, NF1),	/* ESPI_CS0# */
	PAD_CFG_NF(GPP_A5, DN_20K, DEEP, NF1),	/* ESPI_CLK */
	PAD_CFG_NF(GPP_A6, NONE, DEEP, NF1),	/* ESPI_RESET# */
	PAD_CFG_GPI_TRIG_OWN(GPP_A7, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_A8, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_A9, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_NF(GPP_A10, UP_20K, DEEP, NF1),	/* ESPI_ALERT0# */
	PAD_CFG_GPI_TRIG_OWN(GPP_A11, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_A12, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_A13, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_A14, NONE, PLTRST, OFF, ACPI),	/* GPIO */

	/* ------- GPIO Group GPP_C ------- */
	PAD_CFG_NF(GPP_C0, NONE, DEEP, NF1),	/* SMBCLK */
	PAD_CFG_NF(GPP_C1, NONE, DEEP, NF1),	/* SMBDATA */
	PAD_CFG_GPI_TRIG_OWN(GPP_C2, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_NF(GPP_C3, NONE, DEEP, NF3),	/* I2C2_SDA */
	PAD_CFG_NF(GPP_C4, NONE, DEEP, NF3),	/* I2C2_SCL */
	PAD_CFG_NF(GPP_C5, NONE, DEEP, NF1),	/* SML0ALERT# */
	PAD_CFG_GPI_TRIG_OWN(GPP_C6, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_C7, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_C8, NONE, RSMRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_C9, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_C10, NONE, RSMRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_C11, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_C12, NONE, RSMRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_C13, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_C14, NONE, RSMRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_C15, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_NF(GPP_C16, NONE, PLTRST, NF1),	/* I2C0_SDA */
	PAD_CFG_NF(GPP_C17, NONE, PLTRST, NF1),	/* I2C0_SCL */
	PAD_CFG_GPI_TRIG_OWN(GPP_C18, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_C19, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_C20, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_C21, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_C22, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_C23, NONE, PLTRST, OFF, ACPI),	/* GPIO */

	/* ------- GPIO Group vGPIO_3 ------- */
	PAD_CFG_NF(VGPIO_PCIE_0, NONE, PLTRST, NF1),	/* VGPIO_PCIE_0 */
	PAD_CFG_NF(VGPIO_PCIE_1, NONE, PLTRST, NF1),	/* VGPIO_PCIE_1 */
	PAD_CFG_NF(VGPIO_PCIE_2, NONE, PLTRST, NF1),	/* VGPIO_PCIE_2 */
	PAD_CFG_NF(VGPIO_PCIE_3, NONE, PLTRST, NF1),	/* VGPIO_PCIE_3 */
	PAD_CFG_NF(VGPIO_PCIE_4, NONE, PLTRST, NF1),	/* VGPIO_PCIE_4 */
	PAD_CFG_NF(VGPIO_PCIE_5, NONE, PLTRST, NF1),	/* VGPIO_PCIE_5 */
	PAD_CFG_NF(VGPIO_PCIE_6, NONE, PLTRST, NF1),	/* VGPIO_PCIE_6 */
	PAD_CFG_NF(VGPIO_PCIE_7, NONE, PLTRST, NF1),	/* VGPIO_PCIE_7 */
	PAD_CFG_NF(VGPIO_PCIE_8, NONE, PLTRST, NF1),	/* VGPIO_PCIE_8 */
	PAD_CFG_NF(VGPIO_PCIE_9, NONE, PLTRST, NF1),	/* VGPIO_PCIE_9 */
	PAD_CFG_NF(VGPIO_PCIE_10, NONE, PLTRST, NF1),	/* VGPIO_PCIE_10 */
	PAD_CFG_NF(VGPIO_PCIE_11, NONE, PLTRST, NF1),	/* VGPIO_PCIE_11 */
	PAD_CFG_NF(VGPIO_PCIE_12, NONE, PLTRST, NF1),	/* VGPIO_PCIE_12 */
	PAD_CFG_NF(VGPIO_PCIE_13, NONE, PLTRST, NF1),	/* VGPIO_PCIE_13 */
	PAD_CFG_NF(VGPIO_PCIE_14, NONE, PLTRST, NF1),	/* VGPIO_PCIE_14 */
	PAD_CFG_NF(VGPIO_PCIE_15, NONE, PLTRST, NF1),	/* VGPIO_PCIE_15 */
	PAD_CFG_NF(VGPIO_PCIE_16, NONE, PLTRST, NF1),	/* VGPIO_PCIE_16 */
	PAD_CFG_NF(VGPIO_PCIE_17, NONE, PLTRST, NF1),	/* VGPIO_PCIE_17 */
	PAD_CFG_NF(VGPIO_PCIE_18, NONE, PLTRST, NF1),	/* VGPIO_PCIE_18 */
	PAD_CFG_NF(VGPIO_PCIE_19, NONE, PLTRST, NF1),	/* VGPIO_PCIE_19 */
	PAD_CFG_NF(VGPIO_PCIE_20, NONE, PLTRST, NF1),	/* VGPIO_PCIE_20 */
	PAD_CFG_NF(VGPIO_PCIE_21, NONE, PLTRST, NF1),	/* VGPIO_PCIE_21 */
	PAD_CFG_NF(VGPIO_PCIE_22, NONE, PLTRST, NF1),	/* VGPIO_PCIE_22 */
	PAD_CFG_NF(VGPIO_PCIE_23, NONE, PLTRST, NF1),	/* VGPIO_PCIE_23 */
	PAD_CFG_NF(VGPIO_PCIE_24, NONE, PLTRST, NF1),	/* VGPIO_PCIE_24 */
	PAD_CFG_NF(VGPIO_PCIE_25, NONE, PLTRST, NF1),	/* VGPIO_PCIE_25 */
	PAD_CFG_NF(VGPIO_PCIE_26, NONE, PLTRST, NF1),	/* VGPIO_PCIE_26 */
	PAD_CFG_NF(VGPIO_PCIE_27, NONE, PLTRST, NF1),	/* VGPIO_PCIE_27 */
	PAD_CFG_NF(VGPIO_PCIE_28, NONE, PLTRST, NF1),	/* VGPIO_PCIE_28 */
	PAD_CFG_NF(VGPIO_PCIE_29, NONE, PLTRST, NF1),	/* VGPIO_PCIE_29 */
	PAD_CFG_NF(VGPIO_PCIE_30, NONE, PLTRST, NF1),	/* VGPIO_PCIE_30 */
	PAD_CFG_NF(VGPIO_PCIE_31, NONE, PLTRST, NF1),	/* VGPIO_PCIE_31 */
	PAD_CFG_NF(VGPIO_PCIE_32, NONE, PLTRST, NF1),	/* VGPIO_PCIE_32 */
	PAD_CFG_NF(VGPIO_PCIE_33, NONE, PLTRST, NF1),	/* VGPIO_PCIE_33 */
	PAD_CFG_NF(VGPIO_PCIE_34, NONE, PLTRST, NF1),	/* VGPIO_PCIE_34 */
	PAD_CFG_NF(VGPIO_PCIE_35, NONE, PLTRST, NF1),	/* VGPIO_PCIE_35 */
	PAD_CFG_NF(VGPIO_PCIE_36, NONE, PLTRST, NF1),	/* VGPIO_PCIE_36 */
	PAD_CFG_NF(VGPIO_PCIE_37, NONE, PLTRST, NF1),	/* VGPIO_PCIE_37 */
	PAD_CFG_NF(VGPIO_PCIE_38, NONE, PLTRST, NF1),	/* VGPIO_PCIE_38 */
	PAD_CFG_NF(VGPIO_PCIE_39, NONE, PLTRST, NF1),	/* VGPIO_PCIE_39 */
	PAD_CFG_NF(VGPIO_PCIE_40, NONE, PLTRST, NF1),	/* VGPIO_PCIE_40 */
	PAD_CFG_NF(VGPIO_PCIE_41, NONE, PLTRST, NF1),	/* VGPIO_PCIE_41 */
	PAD_CFG_NF(VGPIO_PCIE_42, NONE, PLTRST, NF1),	/* VGPIO_PCIE_42 */
	PAD_CFG_NF(VGPIO_PCIE_43, NONE, PLTRST, NF1),	/* VGPIO_PCIE_43 */
	PAD_CFG_NF(VGPIO_PCIE_44, NONE, PLTRST, NF1),	/* VGPIO_PCIE_44 */
	PAD_CFG_NF(VGPIO_PCIE_45, NONE, PLTRST, NF1),	/* VGPIO_PCIE_45 */
	PAD_CFG_NF(VGPIO_PCIE_46, NONE, PLTRST, NF1),	/* VGPIO_PCIE_46 */
	PAD_CFG_NF(VGPIO_PCIE_47, NONE, PLTRST, NF1),	/* VGPIO_PCIE_47 */
	PAD_CFG_NF(VGPIO_PCIE_48, NONE, PLTRST, NF1),	/* VGPIO_PCIE_48 */
	PAD_CFG_NF(VGPIO_PCIE_49, NONE, PLTRST, NF1),	/* VGPIO_PCIE_49 */
	PAD_CFG_NF(VGPIO_PCIE_50, NONE, PLTRST, NF1),	/* VGPIO_PCIE_50 */
	PAD_CFG_NF(VGPIO_PCIE_51, NONE, PLTRST, NF1),	/* VGPIO_PCIE_51 */
	PAD_CFG_NF(VGPIO_PCIE_52, NONE, PLTRST, NF1),	/* VGPIO_PCIE_52 */
	PAD_CFG_NF(VGPIO_PCIE_53, NONE, PLTRST, NF1),	/* VGPIO_PCIE_53 */
	PAD_CFG_NF(VGPIO_PCIE_54, NONE, PLTRST, NF1),	/* VGPIO_PCIE_54 */
	PAD_CFG_NF(VGPIO_PCIE_55, NONE, PLTRST, NF1),	/* VGPIO_PCIE_55 */
	PAD_CFG_NF(VGPIO_PCIE_56, NONE, PLTRST, NF1),	/* VGPIO_PCIE_56 */
	PAD_CFG_NF(VGPIO_PCIE_57, NONE, PLTRST, NF1),	/* VGPIO_PCIE_57 */
	PAD_CFG_NF(VGPIO_PCIE_58, NONE, PLTRST, NF1),	/* VGPIO_PCIE_58 */
	PAD_CFG_NF(VGPIO_PCIE_59, NONE, PLTRST, NF1),	/* VGPIO_PCIE_59 */
	PAD_CFG_NF(VGPIO_PCIE_60, NONE, PLTRST, NF1),	/* VGPIO_PCIE_60 */
	PAD_CFG_NF(VGPIO_PCIE_61, NONE, PLTRST, NF1),	/* VGPIO_PCIE_61 */
	PAD_CFG_NF(VGPIO_PCIE_62, NONE, PLTRST, NF1),	/* VGPIO_PCIE_62 */
	PAD_CFG_NF(VGPIO_PCIE_63, NONE, PLTRST, NF1),	/* VGPIO_PCIE_63 */
	PAD_CFG_NF(VGPIO_PCIE_64, NONE, PLTRST, NF1),	/* VGPIO_PCIE_64 */
	PAD_CFG_NF(VGPIO_PCIE_65, NONE, PLTRST, NF1),	/* VGPIO_PCIE_65 */
	PAD_CFG_NF(VGPIO_PCIE_66, NONE, PLTRST, NF1),	/* VGPIO_PCIE_66 */
	PAD_CFG_NF(VGPIO_PCIE_67, NONE, PLTRST, NF1),	/* VGPIO_PCIE_67 */
	PAD_CFG_NF(VGPIO_PCIE_68, NONE, PLTRST, NF1),	/* VGPIO_PCIE_68 */
	PAD_CFG_NF(VGPIO_PCIE_69, NONE, PLTRST, NF1),	/* VGPIO_PCIE_69 */
	PAD_CFG_NF(VGPIO_PCIE_70, NONE, PLTRST, NF1),	/* VGPIO_PCIE_70 */
	PAD_CFG_NF(VGPIO_PCIE_71, NONE, PLTRST, NF1),	/* VGPIO_PCIE_71 */
	PAD_CFG_NF(VGPIO_PCIE_72, NONE, PLTRST, NF1),	/* VGPIO_PCIE_72 */
	PAD_CFG_NF(VGPIO_PCIE_73, NONE, PLTRST, NF1),	/* VGPIO_PCIE_73 */
	PAD_CFG_NF(VGPIO_PCIE_74, NONE, PLTRST, NF1),	/* VGPIO_PCIE_74 */
	PAD_CFG_NF(VGPIO_PCIE_75, NONE, PLTRST, NF1),	/* VGPIO_PCIE_75 */
	PAD_CFG_NF(VGPIO_PCIE_76, NONE, PLTRST, NF1),	/* VGPIO_PCIE_76 */
	PAD_CFG_NF(VGPIO_PCIE_77, NONE, PLTRST, NF1),	/* VGPIO_PCIE_77 */
	PAD_CFG_NF(VGPIO_PCIE_78, NONE, PLTRST, NF1),	/* VGPIO_PCIE_78 */
	PAD_CFG_NF(VGPIO_PCIE_79, NONE, PLTRST, NF1),	/* VGPIO_PCIE_79 */
	PAD_CFG_NF(VGPIO_PCIE_80, NONE, DEEP, NF1),	/* VGPIO_PCIE_80 */
	PAD_CFG_NF(VGPIO_PCIE_81, NONE, DEEP, NF1),	/* VGPIO_PCIE_81 */
	PAD_CFG_NF(VGPIO_PCIE_82, NONE, DEEP, NF1),	/* VGPIO_PCIE_82 */
	PAD_CFG_NF(VGPIO_PCIE_83, NONE, DEEP, NF1),	/* VGPIO_PCIE_83 */

	/* ------- GPIO Community 4 ------- */

	/* ------- GPIO Group GPP_S ------- */
	PAD_CFG_GPI_TRIG_OWN(GPP_S0, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_S1, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_S2, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_S3, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_S4, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_S5, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_S6, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_S7, NONE, PLTRST, OFF, ACPI),	/* GPIO */

	/* ------- GPIO Group GPP_E ------- */
	PAD_CFG_GPI_TRIG_OWN(GPP_E0, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_E1, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_E2, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_NC(GPP_E3, NONE),	/* GPIO */
	PAD_CFG_NF(GPP_E4, NONE, PLTRST, NF1),	/* SATA_DEVSLP0 */
	PAD_CFG_NF(GPP_E5, NONE, PLTRST, NF1),	/* SATA_DEVSLP1 */
	PAD_CFG_NF(GPP_E6, NONE, PLTRST, NF1),	/* SATA_DEVSLP2 */
	PAD_CFG_GPI_TRIG_OWN(GPP_E7, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_NF(GPP_E8, NONE, DEEP, NF1),	/* SATALED# */
	PAD_CFG_NF(GPP_E9, NONE, DEEP, NF1),	/* USB_OC0# */
	PAD_CFG_NF(GPP_E10, NONE, DEEP, NF1),	/* USB_OC1# */
	PAD_CFG_NF(GPP_E11, NONE, DEEP, NF1),	/* USB_OC2# */
	PAD_CFG_NF(GPP_E12, NONE, DEEP, NF1),	/* USB_OC3# */
	PAD_CFG_GPI_APIC(GPP_E13, NONE, PLTRST, EDGE_SINGLE, INVERT),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_E14, NONE, RSMRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_E15, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_E16, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_E17, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_E18, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_E19, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_E20, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_E21, NONE, PLTRST, OFF, ACPI),	/* GPIO */

	/* ------- GPIO Group GPP_K ------- */
	PAD_CFG_GPI_APIC(GPP_K0, NONE, PLTRST, EDGE_SINGLE, INVERT),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_K1, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_K2, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_K3, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_K4, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_K5, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_NF(GPP_K6, UP_20K, DEEP, NF2),	/* n/a */
	PAD_CFG_NF(GPP_K7, DN_20K, DEEP, NF2),	/* n/a */
	PAD_CFG_GPO(GPP_K8, 1, PLTRST),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_K9, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_NF(GPP_K10, UP_20K, DEEP, NF2),	/* n/a */
	PAD_CFG_GPI_TRIG_OWN(GPP_K11, NONE, PLTRST, OFF, ACPI),	/* GPIO */

	/* ------- GPIO Group GPP_F ------- */
	PAD_CFG_GPI_TRIG_OWN(GPP_F0, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_F1, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_F2, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_F3, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_F4, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_F5, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_F6, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_F7, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_F8, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_F9, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_F10, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPO(GPP_F11, 1, PLTRST),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_F12, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_F13, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_F14, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_F15, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_F16, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_F17, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_F18, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_F19, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_F20, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_F21, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_F22, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_F23, NONE, PLTRST, OFF, ACPI),	/* GPIO */

	/* ------- GPIO Community 5 ------- */

	/* ------- GPIO Group GPP_D ------- */
	PAD_CFG_GPI_TRIG_OWN(GPP_D0, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_D1, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_D2, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_D3, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_NF(GPP_D4, NONE, DEEP, NF1),	/* SML1CLK */
	PAD_CFG_NF(GPP_D5, NONE, PLTRST, NF2),	/* CNV_RF_RESET# */
	PAD_CFG_NF(GPP_D6, NONE, PLTRST, NF3),	/* MODEM_CLKREQ */
	PAD_CFG_GPI_TRIG_OWN(GPP_D7, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_D8, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_NF(GPP_D9, NONE, DEEP, NF1),	/* SML0CLK */
	PAD_CFG_NF(GPP_D10, NONE, DEEP, NF1),	/* SML0DATA */
	PAD_CFG_NF(GPP_D11, NONE, DEEP, NF1),	/* SRCCLKREQ4# */
	PAD_CFG_GPI_TRIG_OWN(GPP_D12, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_D13, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_D14, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_NF(GPP_D15, NONE, DEEP, NF1),	/* SML1DATA */
	PAD_CFG_GPI_TRIG_OWN(GPP_D16, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_D17, NONE, DEEP, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_D18, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_D19, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_D20, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_D21, NONE, RSMRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_D22, NONE, PLTRST, OFF, ACPI),	/* GPIO */
	PAD_CFG_GPI_TRIG_OWN(GPP_D23, NONE, PLTRST, OFF, ACPI),	/* GPIO */

	/* ------- GPIO Group JTAG ------- */

	/* ------- GPIO Group CPU ------- */
};

#endif /* CFG_GPIO_H */
