# SPDX-License-Identifier: GPL-2.0-or-later
# This is an auto-generated file. Do not edit!!
# Generated by:
# /tmp/go-build/fb/fb4c70f20b6dca62889b41958179d560405c1dd01ff9f38760dde3ea6348053d-d/part_id_gen PTL lp5 src/mainboard/google/atria/variants/atria/memory src/mainboard/google/atria/variants/atria/memory/mem_parts_used.txt

SPD_SOURCES =
SPD_SOURCES += spd/lp5/set-0/spd-11.hex      # ID = 0(0b0000)  Parts = H58G56BK8BX068
