/* SPDX-License-Identifier: GPL-2.0-only */

#ifndef MAINBOARD_GPIO_H
#define MAINBOARD_GPIO_H

#define DGPU_RST_N GPP_F22
#define DGPU_PWR_EN GPP_F23
#define DGPU_GC6 GPP_C12

#ifndef __ACPI__

#include <soc/gpe.h>
#include <soc/gpio.h>

/* Pad configuration in romstage. */
static const struct pad_config early_gpio_table[] = {
		PAD_CFG_TERM_GPO(GPP_F22, 0, NONE, DEEP), // DGPU_RST_N
		PAD_CFG_TERM_GPO(GPP_F23, 0, NONE, DEEP), // DGPU_PWR_EN
};

/* Pad configuration in ramstage. */
static const struct pad_config gpio_table[] = {
		PAD_CFG_NF(GPD0, NONE, DEEP, NF1), // PM_BATLOW#
		PAD_CFG_NF(GPD1, NATIVE, DEEP, NF1), // AC_PRESENT
		PAD_CFG_GPI(GPD2, NATIVE, PWROK), // NC
		PAD_CFG_NF(GPD3, UP_20K, DEEP, NF1), // PWR_BTN#
		PAD_CFG_NF(GPD4, NONE, DEEP, NF1), // SUSB#_PCH
		PAD_CFG_NF(GPD5, NONE, DEEP, NF1), // SUSC#_PCH
		PAD_CFG_NF(GPD6, NONE, DEEP, NF1), // NC
		PAD_CFG_GPI(GPD7, NONE, PWROK), // NC
		PAD_CFG_NF(GPD8, NONE, DEEP, NF1), // SUS_CLK
		PAD_CFG_NF(GPD9, NONE, PWROK, NF1), // NC
		_PAD_CFG_STRUCT(GPD10, 0x04000601, 0x0000), // NC
		PAD_CFG_NF(GPD11, NONE, DEEP, NF1), // NC
		PAD_CFG_TERM_GPO(GPP_A0, 0, NONE, DEEP), // SB_KBCRST#
		PAD_CFG_NF(GPP_A1, NATIVE, DEEP, NF1), // LPC_AD0
		PAD_CFG_NF(GPP_A2, NATIVE, DEEP, NF1), // LPC_AD1
		PAD_CFG_NF(GPP_A3, NATIVE, DEEP, NF1), // LPC_AD2
		PAD_CFG_NF(GPP_A4, NATIVE, DEEP, NF1), // LPC_AD3
		PAD_CFG_NF(GPP_A5, NONE, DEEP, NF1), // LPC_FRAME#
		PAD_CFG_NF(GPP_A6, NONE, DEEP, NF1), // SERIRQ
		PAD_CFG_GPI(GPP_A7, NONE, DEEP), // SCI#_GPP_A7
		PAD_CFG_NF(GPP_A8, NONE, DEEP, NF1), // ECCLKRUN#
		PAD_CFG_NF(GPP_A9, DN_20K, DEEP, NF1), // PCLK_KBC
		PAD_CFG_NF(GPP_A10, DN_20K, DEEP, NF1), // NC
		PAD_CFG_GPI(GPP_A11, UP_20K, DEEP), // NC
		PAD_CFG_GPI(GPP_A12, NONE, DEEP), // NC
		PAD_CFG_NF(GPP_A13, NONE, DEEP, NF1), // SUSWARN#
		PAD_CFG_NF(GPP_A14, NONE, DEEP, NF1), // NC
		PAD_CFG_NF(GPP_A15, UP_20K, DEEP, NF1), // SUS_PWR_ACK#
		PAD_CFG_GPI(GPP_A16, DN_20K, DEEP), // NC
		PAD_CFG_GPI(GPP_A17, NONE, DEEP), // AMP_TYPE_DET
		PAD_CFG_TERM_GPO(GPP_A18, 1, NONE, DEEP), // SB_BLON
		PAD_CFG_GPI(GPP_A19, NONE, DEEP), // NC
		PAD_CFG_TERM_GPO(GPP_A20, 1, NONE, DEEP), // PEX_WAKE#
		PAD_CFG_GPI(GPP_A21, NONE, DEEP), // NC
		PAD_CFG_TERM_GPO(GPP_A22, 1, NONE, DEEP), // SMARTAMP_SW
		PAD_CFG_GPI(GPP_A23, NONE, DEEP), // SMART AMP PWR (L:3.3VS H:3.3V)
		PAD_CFG_GPI(GPP_B0, NONE, DEEP), // TPM_PIRQ#
		PAD_CFG_GPI(GPP_B1, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_B2, NONE, DEEP), // NC
		PAD_CFG_GPI_APIC(GPP_B3, NONE, PLTRST, EDGE_SINGLE, INVERT), // PCH_GPP_B3 (touchpad interrupt)
		PAD_CFG_GPI(GPP_B4, NONE, DEEP), // NC
		PAD_CFG_NF(GPP_B5, NONE, DEEP, NF1), // TBT_CLKREQ#
		PAD_CFG_GPI(GPP_B6, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_B7, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_B8, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_B9, NONE, DEEP), // NC
		PAD_CFG_NF(GPP_B10, NONE, DEEP, NF1), // GLAN_CLKREQ#
		PAD_CFG_GPI(GPP_B11, NONE, DEEP), // NC
		PAD_CFG_NF(GPP_B12, NONE, DEEP, NF1), // SLP_S0#
		_PAD_CFG_STRUCT(GPP_B13, 0x44000601, 0x0000), // PLT_RST#
		PAD_CFG_NF(GPP_B14, NONE, DEEP, NF1), // PCH_SPKR
		PAD_CFG_GPI(GPP_B15, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_B16, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_B17, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_B18, NONE, DEEP), // NO REBOOT STRAP
		PAD_CFG_GPI(GPP_B19, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_B20, NONE, DEEP), // SMI#_GPP_B20
		PAD_CFG_GPI(GPP_B21, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_B22, NONE, DEEP), // BOOT BIOS STRAP
		PAD_CFG_GPI(GPP_B23, NONE, DEEP), // DCI-OOB STRAP
		PAD_CFG_NF(GPP_C0, NONE, DEEP, NF1), // SMB_CLK
		PAD_CFG_NF(GPP_C1, NONE, DEEP, NF1), // SMB_DATA
		_PAD_CFG_STRUCT(GPP_C2, 0x40880100, 0x0000), // CNVI_WAKE#
		PAD_CFG_GPI(GPP_C3, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_C4, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_C5, NONE, DEEP), // WLAN_WAKEUP#
		PAD_CFG_GPI(GPP_C6, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_C7, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_C8, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_C9, NONE, DEEP), // BOARD_ID2
		PAD_CFG_GPI(GPP_C10, NONE, DEEP), //  BOARD_ID1
		PAD_CFG_GPI(GPP_C11, NONE, DEEP), // TBT_DET#
		PAD_CFG_GPI(GPP_C12, NONE, DEEP), // GC6_FB_EN_PCH
		PAD_CFG_GPI(GPP_C13, NONE, DEEP), // TPM_DET
		PAD_CFG_TERM_GPO(GPP_C14, 1, NONE, DEEP), // GPU_EVENT#
		PAD_CFG_GPI(GPP_C15, NONE, DEEP), // 100K pull-down
		PAD_CFG_NF(GPP_C16, NONE, PLTRST, NF1), // TP_DAT_PCH_I2C0
		PAD_CFG_NF(GPP_C17, NONE, PLTRST, NF1), // TP_CLK_PCH_I2C0
		PAD_CFG_NF(GPP_C18, NONE, PLTRST, NF1), // I2C1_SDA
		PAD_CFG_NF(GPP_C19, NONE, PLTRST, NF1), // I2C1_SCL
		PAD_CFG_NF(GPP_C20, NONE, DEEP, NF1), // UART2_RXD
		PAD_CFG_NF(GPP_C21, NONE, DEEP, NF1), // UART2_TXD
		PAD_CFG_NF(GPP_C22, NONE, DEEP, NF1), // UART2_RTS#
		PAD_CFG_NF(GPP_C23, NONE, DEEP, NF1), // UART2_CTS#
		PAD_CFG_GPI(GPP_D0, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_D1, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_D2, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_D3, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_D4, NONE, DEEP), // NC
		PAD_CFG_NF(GPP_D5, NONE, DEEP, NF3), // CNVI_RST#
		PAD_CFG_NF(GPP_D6, NONE, DEEP, NF3), // CNVI_CLKREQ
		PAD_CFG_GPI(GPP_D7, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_D8, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_D9, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_D10, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_D11, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_D12, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_D13, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_D14, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_D15, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_D16, NONE, DEEP), // NC
		PAD_CFG_NF(GPP_D17, NONE, DEEP, NF1), // NC
		PAD_CFG_NF(GPP_D18, NONE, DEEP, NF1), // NC
		PAD_CFG_NF(GPP_D19, NONE, DEEP, NF1), // NC
		PAD_CFG_NF(GPP_D20, NONE, DEEP, NF1), // NC
		PAD_CFG_GPI(GPP_D21, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_D22, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_D23, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_E0, NONE, DEEP), // NC
		PAD_CFG_NF(GPP_E1, UP_20K, DEEP, NF1), // SATAGP1
		PAD_CFG_GPI(GPP_E2, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_E3, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_E4, NONE, DEEP), // NC
		PAD_CFG_NF(GPP_E5, NONE, DEEP, NF1), // SATA_DEVSLP1
		PAD_CFG_TERM_GPO(GPP_E6, 1, NONE, DEEP), // PCH_MUTE#
		PAD_CFG_GPI(GPP_E7, NONE, DEEP), // NC
		PAD_CFG_NF(GPP_E8, NONE, DEEP, NF1), // SATAHDD_LED#
		PAD_CFG_GPI(GPP_E9, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_E10, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_E11, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_E12, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_F0, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_F1, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_F2, NONE, DEEP), // NC
		PAD_CFG_TERM_GPO(GPP_F3, 1, NONE, DEEP), // GPP_F3_LAN_RST#
		PAD_CFG_TERM_GPO(GPP_F4, 1, NONE, DEEP), // GPP_F4_TBT_RST#
		PAD_CFG_GPI(GPP_F5, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_F6, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_F7, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_F8, NONE, DEEP), // NC
		PAD_CFG_TERM_GPO(GPP_F9, 0, NONE, DEEP), // PS8331_SW
		PAD_CFG_GPI(GPP_F10, NONE, DEEP), // BIOS RECOVERY ENABLE STRAP
		PAD_CFG_GPI(GPP_F11, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_F12, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_F13, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_F14, NONE, DEEP), // H_SKTOCC_N
		PAD_CFG_GPI(GPP_F15, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_F16, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_F17, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_F18, NONE, DEEP), // NC
		PAD_CFG_NF(GPP_F19, NONE, DEEP, NF1), // NB_ENAVDD
		PAD_CFG_NF(GPP_F20, NONE, DEEP, NF1), // BLON
		PAD_CFG_NF(GPP_F21, NONE, DEEP, NF1), // EDP_BRIGHTNESS
		PAD_CFG_TERM_GPO(GPP_F22, 1, NONE, DEEP), // DGPU_RST#_PCH
		PAD_CFG_TERM_GPO(GPP_F23, 1, NONE, DEEP), // DGPU_PWR_EN
		PAD_CFG_GPI(GPP_G0, NONE, DEEP), // GSYNC_DET
		PAD_CFG_GPI(GPP_G1, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_G2, NONE, DEEP), // NVSR_DET#
		PAD_CFG_GPI(GPP_G3, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_G4, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_G5, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_G6, NONE, DEEP), // SWI#_GPP_G6
		PAD_CFG_GPI(GPP_G7, NONE, DEEP), // NC
		PAD_CFG_NF(GPP_H0, NONE, DEEP, NF1), // WLAN_CLKREQ#
		PAD_CFG_NF(GPP_H1, NONE, DEEP, NF1), // SD4.0_CLKREQ#
		PAD_CFG_NF(GPP_H2, NONE, DEEP, NF1), // PEG_CLKREQ#
		PAD_CFG_NF(GPP_H3, NONE, DEEP, NF1), // SSD1_CLKREQ#
		PAD_CFG_NF(GPP_H4, NONE, DEEP, NF1), // SSD2_CLKREQ#
		PAD_CFG_GPI(GPP_H5, NONE, DEEP), // NC
		PAD_CFG_TERM_GPO(GPP_H6, 1, NONE, DEEP), // PCIE_SSD1_RST#
		PAD_CFG_TERM_GPO(GPP_H7, 1, NONE, DEEP), // PCIE_SSD2_RST#
		PAD_CFG_GPI(GPP_H8, NONE, DEEP), // GPP_H8_LAN_RST#
		PAD_CFG_GPI(GPP_H9, NONE, DEEP), // TBT_GPIO_WAKE#
		PAD_CFG_GPI(GPP_H10, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_H11, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_H12, NONE, DEEP), // ESPI FLASH SHARING STRAP
		PAD_CFG_GPI(GPP_H13, NONE, DEEP), // TBTA_HRESET
		PAD_CFG_GPI(GPP_H14, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_H15, NONE, DEEP), // RESERVED STRAP
		_PAD_CFG_STRUCT(GPP_H16, 0x44000101, 0x0000), // TBT_RTD3_PWR_EN
		PAD_CFG_TERM_GPO(GPP_H17, 0, NONE, PLTRST), // TBT_FORCE_PWR
		PAD_CFG_TERM_GPO(GPP_H18, 1, NONE, DEEP), // NC
		PAD_CFG_TERM_GPO(GPP_H19, 1, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_H20, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_H21, NONE, DEEP), // XTAL FREQUENCY SELECT STRAP
		PAD_CFG_GPI(GPP_H22, NONE, DEEP), // NC
		_PAD_CFG_STRUCT(GPP_H23, 0x82880100, 0x0000), // TBCIO_PLUG_EVENT#
		PAD_CFG_NF(GPP_I0, NONE, DEEP, NF1), // ANX7411_HPD
		PAD_CFG_NF(GPP_I1, NONE, DEEP, NF1), // HDMI_HPD
		PAD_CFG_NF(GPP_I2, NONE, DEEP, NF1), // MDP_E_HPD
		PAD_CFG_NF(GPP_I3, NONE, DEEP, NF1), // MDP_A_TBT_HPD
		PAD_CFG_NF(GPP_I4, NONE, DEEP, NF1), // SB_IEDP_HPD
		PAD_CFG_TERM_GPO(GPP_I5, 1, NONE, DEEP), // TBT_GPIO_RST#
		PAD_CFG_GPI(GPP_I6, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_I7, NONE, DEEP), // NC
		PAD_CFG_TERM_GPO(GPP_I8, 1, NONE, DEEP), // SSD1_PWR_EN
		PAD_CFG_TERM_GPO(GPP_I9, 1, NONE, DEEP), // SSD2_PWR_EN
		PAD_CFG_GPI(GPP_I10, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_I11, NONE, DEEP), // NC
		PAD_CFG_TERM_GPO(GPP_I12, 1, NONE, DEEP), // SATA_PWR_EN
		PAD_CFG_GPI(GPP_I13, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_I14, NONE, DEEP), // NC
		PAD_CFG_NF(GPP_J0, NONE, DEEP, NF1), // CNVI_GNSS_PA_BLANKING
		PAD_CFG_TERM_GPO(GPP_J1, 1, NONE, DEEP), // GPP_J1
		PAD_CFG_GPI(GPP_J2, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_J3, NONE, DEEP), // NC
		PAD_CFG_NF(GPP_J4, NONE, DEEP, NF1), // CNVI_BRI_DT
		PAD_CFG_NF(GPP_J5, UP_20K, DEEP, NF1), // CNVI_BRI_RSP
		PAD_CFG_NF(GPP_J6, NONE, DEEP, NF1), // CNVI_RGI_DT
		PAD_CFG_NF(GPP_J7, UP_20K, DEEP, NF1), // CNVI_RGI_RSP
		PAD_CFG_NF(GPP_J8, NONE, DEEP, NF1), // CNVI_MFUART2_RXD
		PAD_CFG_NF(GPP_J9, NONE, DEEP, NF1), // CNVI_MFUART2_TXD
		PAD_CFG_GPI(GPP_J10, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_J11, DN_20K, DEEP), // NC
		PAD_CFG_TERM_GPO(GPP_K0, 0, NONE, DEEP), // GPP_K0_SPK_MUTE
		PAD_CFG_TERM_GPO(GPP_K1, 0, NONE, DEEP), // GPP_K1_WOOFER_MUTE
		PAD_CFG_GPI(GPP_K2, NONE, DEEP), // NC
		_PAD_CFG_STRUCT(GPP_K3, 0x40880100, 0x0000), // SCI#_GPP_K3
		PAD_CFG_GPI(GPP_K4, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_K5, NONE, DEEP), // NC
		_PAD_CFG_STRUCT(GPP_K6, 0x40880100, 0x0000), // SWI#_GPP_K6
		PAD_CFG_GPI(GPP_K7, NONE, DEEP), // GPP_K7_LAN_WAKEUP#
		PAD_CFG_TERM_GPO(GPP_K8, 1, NONE, DEEP), // GPP_K8_LAN_RTD3
		PAD_CFG_GPI(GPP_K9, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_K10, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_K11, NONE, DEEP), // NC
		PAD_CFG_TERM_GPO(GPP_K12, 1, NONE, DEEP), // PCH_GPP_K12
		PAD_CFG_GPI(GPP_K13, NONE, DEEP), // NC
		PAD_CFG_TERM_GPO(GPP_K14, 0, NONE, DEEP), // GPP_K14_TEST_R
		_PAD_CFG_STRUCT(GPP_K15, 0x80100100, 0x0000), // GPP_K15_INTP_OUT
		PAD_CFG_GPI(GPP_K16, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_K17, NONE, DEEP), // NC
		PAD_CFG_TERM_GPO(GPP_K18, 1, NONE, DEEP), // GPP_K18_TBT_WAKE#
		_PAD_CFG_STRUCT(GPP_K19, 0x42800101, 0x0000), // SMI#_GPP_K19
		PAD_CFG_GPI(GPP_K20, NONE, DEEP), // NC
		PAD_CFG_GPI(GPP_K21, NONE, DEEP), // NC
		_PAD_CFG_STRUCT(GPP_K22, 0x44000101, 0x0000), // NC
		PAD_CFG_GPI(GPP_K23, NONE, DEEP), // NC
};

#endif

#endif
