/* SPDX-License-Identifier: GPL-2.0-only */

#ifndef MAINBOARD_GPIO_H
#define MAINBOARD_GPIO_H

#ifndef __ACPI__

#include <soc/gpe.h>
#include <soc/gpio.h>

/* Pad configuration in romstage. */
static const struct pad_config early_gpio_table[] = {
		//TODO: add early GPIO settings
		PAD_CFG_TERM_GPO(GPP_F22, 1, UP_20K, DEEP), // DGPU_RST#_PCH
		PAD_CFG_TERM_GPO(GPP_K22, 0, UP_5K, DEEP), // GPU_PWR_EN#
};

/* Pad configuration in ramstage. */
static const struct pad_config gpio_table[] = {
		//TODO: GPIO names and verify everything
		PAD_CFG_NF(GPD0, NONE, DEEP, NF1),
		PAD_CFG_NF(GPD1, NATIVE, DEEP, NF1),
		PAD_CFG_GPI(GPD2, NATIVE, PWROK),
		PAD_CFG_NF(GPD3, UP_20K, DEEP, NF1),
		PAD_CFG_NF(GPD4, NONE, DEEP, NF1),
		PAD_CFG_NF(GPD5, NONE, DEEP, NF1),
		PAD_CFG_NF(GPD6, UP_20K, PWROK, NF1),
		PAD_CFG_GPI(GPD7, UP_20K, PWROK),
		PAD_CFG_NF(GPD8, NONE, DEEP, NF1),
		PAD_CFG_NF(GPD9, NONE, DEEP, NF1),
		PAD_CFG_NF(GPD10, NONE, DEEP, NF1),
		PAD_CFG_GPI(GPD11, UP_20K, PWROK),
		PAD_CFG_NF(GPP_A0, NONE, DEEP, NF1),
		PAD_CFG_NF(GPP_A1, NONE, DEEP, NF1),
		PAD_CFG_NF(GPP_A2, NONE, DEEP, NF1),
		PAD_CFG_NF(GPP_A3, NONE, DEEP, NF1),
		PAD_CFG_NF(GPP_A4, NONE, DEEP, NF1),
		PAD_CFG_NF(GPP_A5, NONE, DEEP, NF1),
		PAD_CFG_NF(GPP_A6, NONE, DEEP, NF1),
		PAD_CFG_NF(GPP_A7, NONE, DEEP, NF1),
		PAD_CFG_NF(GPP_A8, NONE, DEEP, NF1),
		PAD_CFG_NF(GPP_A9, NONE, DEEP, NF1),
		PAD_CFG_NF(GPP_A10, UP_20K, DEEP, NF1),
		_PAD_CFG_STRUCT(GPP_A11, 0x80100100, 0x0000),
		PAD_CFG_GPI(GPP_A12, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_A13, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_A14, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_A15, UP_20K, DEEP),
		PAD_CFG_NF(GPP_A16, NONE, DEEP, NF1),
		PAD_CFG_GPI(GPP_A17, UP_20K, DEEP),
		PAD_CFG_TERM_GPO(GPP_A18, 1, NONE, DEEP),
		PAD_CFG_GPI(GPP_A19, UP_20K, DEEP),
		PAD_CFG_TERM_GPO(GPP_A20, 1, NONE, DEEP),
		PAD_CFG_GPI(GPP_A21, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_A22, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_A23, UP_20K, DEEP),
		_PAD_CFG_STRUCT(GPP_B0, 0x42080100, 0x3000), // TPM_PIRQ#
		PAD_CFG_GPI(GPP_B1, UP_20K, DEEP),
		PAD_CFG_NF(GPP_B2, NONE, DEEP, NF1),
		PAD_CFG_TERM_GPO(GPP_B3, 1, NONE, DEEP),
		PAD_CFG_GPI(GPP_B4, UP_20K, DEEP),
		PAD_CFG_NF(GPP_B5, NONE, DEEP, NF1), // WLAN_CLKREQ#
		PAD_CFG_NF(GPP_B6, NONE, DEEP, NF1), // GLAN_CLKREQ#
		PAD_CFG_GPI(GPP_B7, UP_20K, PLTRST), // GPIO_CR_RESET_R
		PAD_CFG_GPI(GPP_B8, UP_20K, PLTRST), // CR_GPIO_WAKE_N_R
		PAD_CFG_NF(GPP_B9, NONE, DEEP, NF1), // CR_CLKREQ#
		PAD_CFG_GPI(GPP_B10, UP_20K, PLTRST), // PRSNT#
		PAD_CFG_TERM_GPO(GPP_B11, 1, NONE, DEEP),
		PAD_CFG_NF(GPP_B12, NONE, DEEP, NF1),
		PAD_CFG_NF(GPP_B13, NONE, DEEP, NF1),
		PAD_CFG_NF(GPP_B14, NONE, DEEP, NF1),
		PAD_CFG_GPI(GPP_B15, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_B16, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_B17, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_B18, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_B19, UP_20K, DEEP),
		_PAD_CFG_STRUCT(GPP_B20, 0x42040100, 0x0000),
		PAD_CFG_GPI(GPP_B21, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_B22, UP_20K, DEEP),
		PAD_CFG_NF(GPP_B23, NONE, DEEP, NF2),
		PAD_CFG_NF(GPP_C0, NONE, DEEP, NF1),
		PAD_CFG_NF(GPP_C1, NONE, DEEP, NF1),
		PAD_CFG_GPI(GPP_C2, UP_20K, DEEP),
		PAD_CFG_NF(GPP_C3, NONE, DEEP, NF1),
		PAD_CFG_NF(GPP_C4, NONE, DEEP, NF1),
		PAD_CFG_NF(GPP_C5, NONE, DEEP, NF1),
		PAD_CFG_NF(GPP_C6, NONE, DEEP, NF1),
		PAD_CFG_NF(GPP_C7, NONE, DEEP, NF1),
		PAD_CFG_GPI(GPP_C8, NONE, PLTRST),
		PAD_CFG_GPI(GPP_C9, NONE, DEEP),
		PAD_CFG_GPI(GPP_C10, DN_20K, DEEP),
		PAD_CFG_TERM_GPO(GPP_C11, 1, NONE, DEEP),
		PAD_CFG_GPI(GPP_C12, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_C13, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_C14, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_C15, UP_20K, DEEP),
		PAD_CFG_NF(GPP_C16, NONE, PLTRST, NF1),
		PAD_CFG_NF(GPP_C17, NONE, PLTRST, NF1),
		PAD_CFG_NF(GPP_C18, NONE, PLTRST, NF1),
		PAD_CFG_NF(GPP_C19, NONE, PLTRST, NF1),
		PAD_CFG_NF(GPP_C20, NONE, PLTRST, NF1),
		PAD_CFG_NF(GPP_C21, NONE, PLTRST, NF1),
		PAD_CFG_GPI(GPP_C22, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_C23, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_D0, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_D1, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_D2, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_D3, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_D4, UP_20K, DEEP),
		PAD_CFG_NF(GPP_D5, NONE, DEEP, NF3),
		PAD_CFG_NF(GPP_D6, NONE, DEEP, NF3),
		PAD_CFG_NF(GPP_D7, NONE, PLTRST, NF1),
		PAD_CFG_NF(GPP_D8, NONE, PLTRST, NF1),
		PAD_CFG_GPI(GPP_D9, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_D10, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_D11, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_D12, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_D13, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_D14, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_D15, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_D16, UP_20K, DEEP),
		PAD_CFG_NF(GPP_D17, UP_20K, DEEP, NF1),
		PAD_CFG_NF(GPP_D18, UP_20K, DEEP, NF1),
		PAD_CFG_NF(GPP_D19, UP_20K, DEEP, NF1),
		PAD_CFG_NF(GPP_D20, UP_20K, DEEP, NF1),
		PAD_CFG_GPI(GPP_D21, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_D22, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_D23, UP_20K, DEEP),
		PAD_CFG_NF(GPP_E0, NONE, DEEP, NF2),
		PAD_CFG_NF(GPP_E1, NONE, DEEP, NF1), // M.2_SSD1_DET_N
		PAD_CFG_NF(GPP_E2, NONE, DEEP, NF2), // VCCIO_0_CTRL
		PAD_CFG_GPI(GPP_E3, UP_20K, DEEP), // SMI#
		PAD_CFG_GPI(GPP_E4, UP_20K, DEEP),
		PAD_CFG_NF(GPP_E5, NONE, DEEP, NF1),
		PAD_CFG_NF(GPP_E6, NONE, DEEP, NF1),
		PAD_CFG_GPI_APIC(GPP_E7, NONE, PLTRST, EDGE_SINGLE, INVERT), // TP_ATTN#
		PAD_CFG_NF(GPP_E8, NONE, DEEP, NF1), // PCH_SATAHDD_LED#
		PAD_CFG_GPI(GPP_E9, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_E10, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_E11, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_E12, UP_20K, DEEP),
		PAD_CFG_NF(GPP_F0, NONE, DEEP, NF2),
		PAD_CFG_NF(GPP_F1, NONE, DEEP, NF1), // M.2_SSD2_DET_N
		PAD_CFG_TERM_GPO(GPP_F2, 1, UP_20K, PLTRST), // GPP_F2_TBT_RST#
		PAD_CFG_NF(GPP_F3, NONE, DEEP, NF2),
		PAD_CFG_NF(GPP_F4, NONE, DEEP, NF2),
		PAD_CFG_NF(GPP_F5, NONE, DEEP, NF1),
		PAD_CFG_NF(GPP_F6, NONE, DEEP, NF1),
		PAD_CFG_GPI(GPP_F7, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_F8, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_F9, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_F10, UP_20K, DEEP), // PCH_CONFIG_JUMPER
		PAD_CFG_TERM_GPO(GPP_F11, 0, NONE, DEEP), // SSD1_PWR_DN#
		PAD_CFG_GPI(GPP_F12, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_F13, UP_20K, DEEP),
		PAD_CFG_NF(GPP_F14, NONE, DEEP, NF2),
		PAD_CFG_GPI(GPP_F15, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_F16, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_F17, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_F18, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_F19, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_F20, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_F21, UP_20K, DEEP),
		PAD_CFG_TERM_GPO(GPP_F22, 1, UP_20K, DEEP), // DGPU_RST#_PCH
		PAD_CFG_TERM_GPO(GPP_F23, 0, NONE, DEEP), // GC_OFF_EN
		PAD_CFG_GPI(GPP_G0, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_G1, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_G2, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_G3, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_G4, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_G5, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_G6, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_G7, UP_20K, DEEP),
		PAD_CFG_NF(GPP_H0, NONE, DEEP, NF1), // TBT_CLKREQ#
		PAD_CFG_NF(GPP_H1, NONE, DEEP, NF1), // MXM_REQ#
		PAD_CFG_NF(GPP_H2, NONE, DEEP, NF1), // SSD_CLKREQ#
		PAD_CFG_GPI(GPP_H3, NONE, PLTRST),
		PAD_CFG_NF(GPP_H4, NONE, DEEP, NF1), // PE_CLKREQ#
		PAD_CFG_GPI(GPP_H5, NONE, PLTRST),
		PAD_CFG_GPI(GPP_H6, NONE, PLTRST), // WLAN_GPIO_WAKE_N
		PAD_CFG_TERM_GPO(GPP_H7, 0, NONE, DEEP), // PCIE_SSD2_RESET
		PAD_CFG_NF(GPP_H8, NONE, DEEP, NF1), // SSD2_CLKREQ#
		PAD_CFG_NF(GPP_H9, NONE, DEEP, NF1), // SSD3_CLKREQ#
		PAD_CFG_NF(GPP_H10, NONE, PLTRST, NF1),
		PAD_CFG_TERM_GPO(GPP_H11, 0, NONE, DEEP), // SSD3_PWR_DN#
		PAD_CFG_GPI(GPP_H12, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_H13, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_H14, UP_20K, DEEP),
		_PAD_CFG_STRUCT(GPP_H15, 0x40880100, 0x3000),
		PAD_CFG_GPI(GPP_H16, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_H17, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_H18, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_H19, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_H20, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_H21, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_H22, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_H23, UP_20K, DEEP),
		_PAD_CFG_STRUCT(GPP_I0, 0x46080100, 0x0000),
		_PAD_CFG_STRUCT(GPP_I1, 0x46080100, 0x0000),
		_PAD_CFG_STRUCT(GPP_I2, 0x46080100, 0x0000),
		_PAD_CFG_STRUCT(GPP_I3, 0x46080100, 0x0000),
		PAD_CFG_NF(GPP_I4, NONE, DEEP, NF1),
		PAD_CFG_TERM_GPO(GPP_I5, 0, NONE, DEEP), // GPIO_TBT_RESET
		PAD_CFG_GPI(GPP_I6, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_I7, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_I8, UP_20K, DEEP),
		PAD_CFG_TERM_GPO(GPP_I9, 1, NONE, DEEP),
		PAD_CFG_TERM_GPO(GPP_I10, 0, NONE, DEEP),
		PAD_CFG_GPI(GPP_I11, UP_20K, DEEP),
		PAD_CFG_TERM_GPO(GPP_I12, 0, NONE, DEEP),
		PAD_CFG_TERM_GPO(GPP_I13, 0, NONE, DEEP),
		PAD_CFG_GPI(GPP_I14, UP_20K, DEEP),
		PAD_CFG_NF(GPP_J0, NONE, DEEP, NF1),
		PAD_CFG_NF(GPP_J1, NONE, DEEP, NF2),
		PAD_CFG_GPI(GPP_J2, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_J3, UP_20K, DEEP),
		PAD_CFG_NF(GPP_J4, NONE, DEEP, NF1),
		PAD_CFG_NF(GPP_J5, UP_20K, DEEP, NF1),
		PAD_CFG_NF(GPP_J6, NONE, DEEP, NF1),
		PAD_CFG_NF(GPP_J7, UP_20K, DEEP, NF1),
		PAD_CFG_NF(GPP_J8, NONE, DEEP, NF1),
		PAD_CFG_NF(GPP_J9, UP_20K, DEEP, NF1),
		PAD_CFG_GPI(GPP_J10, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_J11, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_K0, UP_20K, DEEP), // PCH_GPIO_PK_MUTE
		PAD_CFG_GPI(GPP_K1, UP_20K, DEEP), // PCH_GPIO_WOOFER_MUTE
		PAD_CFG_GPI(GPP_K2, UP_20K, DEEP), // DGPU_PWRGD
		_PAD_CFG_STRUCT(GPP_K3, 0x80880100, 0x3000), // SCI#
		PAD_CFG_GPI(GPP_K4, UP_20K, DEEP), // GPU_EVENT#_R
		PAD_CFG_TERM_GPO(GPP_K5, 0, NONE, DEEP), // DP_MUX_SW
		_PAD_CFG_STRUCT(GPP_K6, 0x40880100, 0x0000), // SWI#
		PAD_CFG_GPI(GPP_K7, UP_20K, DEEP), // E3100_PWR_EN
		PAD_CFG_TERM_GPO(GPP_K8, 0, NONE, DEEP), // SSD4_PWR_DN#
		PAD_CFG_GPI(GPP_K9, UP_20K, DEEP), // TBTA_HRESET
		PAD_CFG_GPI(GPP_K10, UP_20K, DEEP), // MIC_SENSE_PCH
		PAD_CFG_GPI(GPP_K11, UP_20K, DEEP), // XFI_SENSE_PCH
		_PAD_CFG_STRUCT(GPP_K12, 0x82880100, 0x3000),
		PAD_CFG_GPI(GPP_K13, UP_20K, DEEP),
		PAD_CFG_TERM_GPO(GPP_K14, 0, NONE, DEEP),
		PAD_CFG_GPI(GPP_K15, UP_20K, DEEP),
		PAD_CFG_TERM_GPO(GPP_K16, 1, UP_20K, DEEP), // TBT_FORCE_PWR_R
		PAD_CFG_GPI(GPP_K17, UP_20K, DEEP),
		PAD_CFG_TERM_GPO(GPP_K18, 1, NONE, DEEP),
		PAD_CFG_GPI(GPP_K19, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_K20, UP_20K, DEEP),
		PAD_CFG_GPI(GPP_K21, NONE, DEEP), // GC6_FB_EN
		PAD_CFG_TERM_GPO(GPP_K22, 0, UP_5K, DEEP), // GPU_PWR_EN#
		PAD_CFG_TERM_GPO(GPP_K23, 1, NONE, PLTRST), // TBT_RTD3_PWR_EN_R
};

#endif

#endif
