# SPDX-License-Identifier: GPL-2.0-or-later
# This is an auto-generated file. Do not edit!!
# Generated by:
# util/spd_tools/bin/part_id_gen PTL lp5 src/mainboard/system76/ptl/variants/lemp14/memory src/mainboard/system76/ptl/variants/lemp14/memory/mem_parts_used.txt

SPD_SOURCES =
SPD_SOURCES += spd/lp5/set-0/spd-2.hex      # ID = 0(0b0000)  Parts = MT62F1G32D4DR-031 WT:B
