/* SPDX-License-Identifier: GPL-2.0-only */

#include <mainboard/gpio.h>
#include <soc/gpio.h>

static const struct pad_config gpio_table[] = {
	PAD_CFG_NF(GPP_A00, NONE, DEEP, NF1), // ESPI_IO0_EC
	PAD_CFG_GPO(GPP_A01, 1, DEEP), // ESPI_IO1_EC
	PAD_CFG_GPO(GPP_A02, 1, DEEP), // ESPI_IO2_EC
	PAD_CFG_GPO(GPP_A03, 1, DEEP), // ESPI_IO3_EC
	PAD_CFG_GPO(GPP_A04, 1, DEEP), // ESPI_CS_EC#
	PAD_CFG_GPO(GPP_A05, 1, DEEP), // ESPI_CLK_EC
	PAD_CFG_GPO(GPP_A06, 1, DEEP), // ESPI_RESET#
	PAD_CFG_GPO(GPP_A07, 1, DEEP),
	PAD_CFG_NF(GPP_A08, NONE, DEEP, NF1), // SD_PWR_EN
	PAD_CFG_NF(GPP_A09, NONE, DEEP, NF1),
	PAD_CFG_NF(GPP_A10, UP_20K, DEEP, NF1),
	PAD_CFG_NF(GPP_A11, UP_20K, DEEP, NF1), // WLAN_RST#
	PAD_NC(GPP_A12, NATIVE), // WLAN_WAKEUP#
	PAD_CFG_NF(GPP_A13, NATIVE, DEEP, NF2), // BODYSAR#
	_PAD_CFG_STRUCT(GPP_A14, 0x40001300, 0x3c00),
	PAD_CFG_NF(GPP_A15, UP_20K, DEEP, NF1),
	PAD_CFG_NF(GPP_A16, UP_20K, DEEP, NF1), // PCH_BT_EN
	PAD_CFG_NF(GPP_A17, UP_20K, DEEP, NF1), // WIFI_RF_EN

	PAD_CFG_NF(GPP_B00, NONE, PWROK, NF1), // TBT_I2C_SCL
	PAD_CFG_NF(GPP_B01, NONE, PWROK, NF1), // TBT_I2C_SDA
	PAD_CFG_GPO(GPP_B02, 1, DEEP),
	PAD_CFG_GPO(GPP_B03, 1, DEEP),
	PAD_CFG_GPO(GPP_B04, 1, DEEP), // strap
	PAD_CFG_GPO(GPP_B05, 1, DEEP),
	PAD_CFG_GPO(GPP_B06, 0, PLTRST), // ROM_I2C_EN
	PAD_CFG_GPO(GPP_B07, 1, DEEP),
	PAD_CFG_GPO(GPP_B08, 1, DEEP),
	PAD_CFG_GPO(GPP_B09, 1, PLTRST), // M2_SSD1_RST#
	PAD_CFG_GPO(GPP_B10, 1, PLTRST), // SSD1_PWR_EN
	PAD_NC(GPP_B11, NONE),
	PAD_CFG_NF(GPP_B12, NONE, DEEP, NF1), // SLP_S0#
	PAD_CFG_NF(GPP_B13, NONE, DEEP, NF1), // PLT_RST#
	PAD_CFG_NF(GPP_B14, NONE, DEEP, NF2), // CPU_HDMI_HPD
	PAD_NC(GPP_B15, NONE), // USB_OC3#
	PAD_CFG_GPO(GPP_B16, 1, DEEP),
	PAD_CFG_GPO(GPP_B17, 1, DEEP), // HDMI_EN
	PAD_CFG_GPO(GPP_B18, 1, DEEP),
	PAD_CFG_GPO(GPP_B19, 1, DEEP),
	PAD_NC(GPP_B20, NONE), // LTE_RST_N
	PAD_CFG_GPO(GPP_B21, 0, PLTRST), // DG_FORCE_PWR
	PAD_CFG_GPO(GPP_B22, 1, DEEP),
	PAD_CFG_GPO(GPP_B23, 1, DEEP), // strap
	PAD_CFG_GPO(GPP_B24, 1, DEEP),
	PAD_CFG_GPO(GPP_B25, 1, DEEP),

	PAD_CFG_NF(GPP_C00, UP_20K, DEEP, NF1),
	PAD_CFG_NF(GPP_C01, UP_20K, DEEP, NF1),
	PAD_CFG_GPO(GPP_C02, 1, DEEP), // strap
	PAD_CFG_NF(GPP_C03, NONE, DEEP, NF1), // SML0_CLK
	PAD_CFG_NF(GPP_C04, NONE, DEEP, NF1), // SML0_DATA
	PAD_CFG_GPO(GPP_C05, 1, DEEP), // strap
	PAD_NC(GPP_C06, NONE),
	PAD_NC(GPP_C07, NONE),
	PAD_CFG_GPO(GPP_C08, 1, DEEP),
	PAD_CFG_GPO(GPP_C09, 1, DEEP),
	PAD_CFG_GPO(GPP_C10, 1, DEEP),
	PAD_CFG_GPO(GPP_C11, 1, DEEP),
	PAD_CFG_NF(GPP_C12, NONE, PLTRST, NF1), // CARD_CLKREQ#_N
	PAD_CFG_NF(GPP_C13, NONE, PLTRST, NF1), // WLAN_CLKREQ#_N
	PAD_CFG_NF(GPP_C14, NONE, PLTRST, NF1), // 5G_PCIE_CLKREQ#_N
	PAD_CFG_GPO(GPP_C15, 1, DEEP), // strap
	//TODO PAD_CFG_NF(GPP_C16, NONE, TODO_0xc4000700, NF1), // TBTA_LSX0_TXD
	//TODO PAD_CFG_NF(GPP_C17, NONE, TODO_0xc4000700, NF1), // TBTA_LSX0_RXD
	PAD_CFG_GPO(GPP_C18, 1, DEEP),
	PAD_CFG_GPO(GPP_C19, 1, DEEP),
	PAD_CFG_GPO(GPP_C20, 1, DEEP),
	PAD_CFG_GPO(GPP_C21, 1, DEEP),
	PAD_CFG_NF(GPP_C22, NONE, DEEP, NF2), // HDMI_CTRLCLK
	PAD_CFG_NF(GPP_C23, NONE, DEEP, NF2), // HDMI_CTRLDATA

	PAD_CFG_GPO(GPP_D00, 1, PLTRST), // SB_BLON
	PAD_CFG_GPO(GPP_D01, 1, DEEP),
	PAD_CFG_GPO(GPP_D02, 1, DEEP),
	PAD_CFG_GPO(GPP_D03, 1, DEEP),
	PAD_CFG_GPO(GPP_D04, 1, DEEP),
	PAD_CFG_GPO(GPP_D05, 1, DEEP),
	PAD_CFG_GPO(GPP_D06, 1, DEEP),
	PAD_CFG_GPO(GPP_D07, 1, DEEP),
	PAD_CFG_GPO(GPP_D08, 1, DEEP),
	PAD_CFG_GPO(GPP_D09, 1, DEEP),
	PAD_CFG_NF(GPP_D10, NONE, DEEP, NF1), // HDA_BITCLK
	PAD_CFG_NF(GPP_D11, NATIVE, DEEP, NF1), // HDA_SYNC
	PAD_CFG_NF(GPP_D12, NATIVE, DEEP, NF1), // HDA_SDOUT / strap
	PAD_CFG_NF(GPP_D13, NATIVE, DEEP, NF1), // HDA_SDIN0
	PAD_CFG_GPO(GPP_D14, 1, DEEP),
	PAD_NC(GPP_D15, NONE), // CNVI_WAKE#
	PAD_CFG_NF(GPP_D16, NONE, DEEP, NF1), // HDA_RST#
	PAD_CFG_GPO(GPP_D17, 1, DEEP),
	PAD_CFG_NF(GPP_D18, NONE, PLTRST, NF1), // SSD1_CLKREQ#_N
	PAD_CFG_GPO(GPP_D19, 1, PLTRST), // SD_PCIE_RST_N
	PAD_CFG_GPO(GPP_D20, 1, DEEP),
	PAD_CFG_GPO(GPP_D21, 1, DEEP),
	PAD_CFG_NF(GPP_D22, NATIVE, DEEP, NF1),
	PAD_CFG_NF(GPP_D23, NATIVE, DEEP, NF1),
	PAD_CFG_GPO(GPP_D24, 1, DEEP),
	PAD_CFG_GPO(GPP_D25, 1, DEEP),

	_PAD_CFG_STRUCT(GPP_E01, 0x42880100, 0x0000), // TPM_PIRQ#
	PAD_NC(GPP_E02, NONE), // VRALERT#
	PAD_CFG_GPO(GPP_E03, 1, DEEP),
	PAD_CFG_GPO(GPP_E04, 1, DEEP),
	PAD_CFG_GPO(GPP_E05, 1, DEEP),
	PAD_CFG_GPO(GPP_E06, 1, DEEP), // strap
	PAD_CFG_GPO(GPP_E07, 1, DEEP),
	PAD_NC(GPP_E08, NONE), // WAKE_ON_WWAN_N
	PAD_NC(GPP_E09, NONE), // USB_OC0#
	PAD_CFG_GPO(GPP_E10, 1, DEEP),
	PAD_CFG_GPI(GPP_E11, NONE, DEEP), // BOARD_ID1
	_PAD_CFG_STRUCT(GPP_E12, 0x44002300, 0x0000), // AMP_SMB_CLK
	_PAD_CFG_STRUCT(GPP_E13, 0x44002300, 0x0000), // AMP_SMB_DATA
	PAD_CFG_GPI(GPP_E14, NONE, DEEP), // BOARD_ID2
	PAD_CFG_GPI(GPP_E15, NONE, DEEP), // BOARD_ID3
	PAD_CFG_GPO(GPP_E16, 1, DEEP),
	PAD_CFG_GPI(GPP_E17, NONE, DEEP), // BOARD_ID4
	PAD_CFG_GPO(GPP_E18, 1, DEEP),
	PAD_CFG_GPO(GPP_E19, 1, DEEP),
	PAD_CFG_GPO(GPP_E20, 1, DEEP),
	PAD_CFG_NF(GPP_E21, NONE, PWROK, NF1), // TBT_I2C_INT
	PAD_CFG_GPO(GPP_E22, 1, DEEP),

	PAD_CFG_NF(GPP_F00, NONE, DEEP, NF1), // CNVI_BRI_DT
	PAD_CFG_NF(GPP_F01, UP_20K, DEEP, NF1), // CNVI_BRI_RSP
	PAD_CFG_NF(GPP_F02, NONE, DEEP, NF1), // CNVI_RGI_DT
	PAD_CFG_NF(GPP_F03, UP_20K, DEEP, NF1), // CNVI_RGI_RSP
	PAD_CFG_NF(GPP_F04, NONE, DEEP, NF1), // CNVI_RST#
	PAD_CFG_NF(GPP_F05, NONE, DEEP, NF3), // CNVI_CLKREQ
	PAD_CFG_GPO(GPP_F06, 1, DEEP), // CNVI_GNSS_PA_BLANKING
	PAD_CFG_GPO(GPP_F07, 1, DEEP),
	PAD_CFG_GPO(GPP_F08, 1, DEEP),
	PAD_CFG_GPI(GPP_F09, NONE, DEEP), // TPM_DET
	PAD_CFG_GPO(GPP_F10, 1, DEEP),
	PAD_CFG_GPO(GPP_F11, 1, DEEP),
	_PAD_CFG_STRUCT(GPP_F12, 0x44002300, 0x0000), // I2C_SCL_TP
	_PAD_CFG_STRUCT(GPP_F13, 0x44002300, 0x0000), // I2C_SDA_TP
	PAD_CFG_GPO(GPP_F14, 1, DEEP),
	PAD_CFG_GPO(GPP_F15, 1, DEEP),
	PAD_CFG_GPO(GPP_F16, 1, PLTRST), // CCD_WP#
	PAD_CFG_GPO(GPP_F17, 1, DEEP),
	_PAD_CFG_STRUCT(GPP_F18, 0x80800100, 0x0000), // TP_ATTN#_N
	PAD_CFG_GPO(GPP_F19, 1, DEEP), // strap
	PAD_CFG_GPO(GPP_F20, 1, DEEP),
	PAD_CFG_GPO(GPP_F21, 1, DEEP),
	PAD_CFG_GPO(GPP_F22, 1, DEEP),
	PAD_CFG_GPO(GPP_F23, 1, DEEP),

	PAD_CFG_NF(GPP_H00, NONE, DEEP, NF1), // strap
	PAD_CFG_NF(GPP_H01, NONE, DEEP, NF1), // strap
	PAD_CFG_NF(GPP_H02, NONE, DEEP, NF1), // strap
	PAD_CFG_NF(GPP_H03, NONE, DEEP, NF1), // PCH_MUTE
	PAD_CFG_NF(GPP_H04, NONE, DEEP, NF1), // CNVI_MFUART2_RXD
	PAD_CFG_NF(GPP_H05, NONE, DEEP, NF1), // CNVI_MFUART2_TXD
	PAD_CFG_NF(GPP_H06, UP_20K, DEEP, NF1),
	PAD_CFG_NF(GPP_H07, NONE, DEEP, NF1),
	PAD_CFG_NF(GPP_H08, NONE, DEEP, NF1), // UART_RX
	PAD_CFG_NF(GPP_H09, UP_20K, DEEP, NF1), // UART_TX
	PAD_CFG_NF(GPP_H10, UP_20K, DEEP, NF1),
	PAD_CFG_NF(GPP_H11, DN_20K, DEEP, NF1),
	//TODO: PAD_CFG_NF(GPP_H12, TODO_0x2400, DEEP, NF1),
	PAD_CFG_NF(GPP_H13, DN_20K, DEEP, NF1), // CPU_C10_GATE#
	PAD_CFG_NF(GPP_H14, NONE, DEEP, NF1),
	PAD_CFG_GPO(GPP_H15, 1, DEEP),
	PAD_CFG_GPO(GPP_H16, 1, DEEP),
	PAD_CFG_GPO(GPP_H17, 1, DEEP),
	PAD_NC(GPP_H18, NONE),
	_PAD_CFG_STRUCT(GPP_H19, 0x44000601, 0x0000),
	_PAD_CFG_STRUCT(GPP_H20, 0x44000601, 0x0000),
	PAD_CFG_GPO(GPP_H21, 1, DEEP), // PCH_I2C_SDA
	PAD_CFG_GPO(GPP_H22, 1, DEEP), // PCH_I2C_SCL
	PAD_NC(GPP_H23, NONE),
	PAD_NC(GPP_H24, NONE),

	PAD_CFG_GPO(GPP_S00, 1, DEEP),
	PAD_CFG_GPO(GPP_S01, 1, DEEP),
	PAD_CFG_GPO(GPP_S02, 1, DEEP), // DMIC_CLK
	PAD_CFG_GPO(GPP_S03, 1, DEEP), // DMIC_DATA
	PAD_CFG_GPO(GPP_S04, 1, DEEP), // BT_PCMCLK
	PAD_CFG_GPO(GPP_S05, 1, DEEP), // BT_PCMFRM
	PAD_CFG_GPO(GPP_S06, 1, DEEP), // BT_PCMOUT
	PAD_CFG_GPO(GPP_S07, 1, DEEP), // BT_PCMIN

	PAD_CFG_NF(GPP_V00, UP_20K, DEEP, NF1),
	PAD_CFG_NF(GPP_V01, NATIVE, DEEP, NF1), // AC_PRESENT
	PAD_CFG_NF(GPP_V02, NATIVE, DEEP, NF1), // SOC_WAKE#
	PAD_CFG_NF(GPP_V03, UP_20K, DEEP, NF1), // CPU_PWR_BTN#
	PAD_CFG_NF(GPP_V04, NONE, DEEP, NF1), // SUSB#_PCH
	PAD_CFG_NF(GPP_V05, NONE, DEEP, NF1), // SUSC#_PCH
	PAD_CFG_NF(GPP_V06, NONE, DEEP, NF1), // SLP_A#
	PAD_CFG_NF(GPP_V07, NONE, DEEP, NF1), // SUS_CLK
	PAD_CFG_GPO(GPP_V08, 1, DEEP), // SLP_WLAN#
	PAD_CFG_GPO(GPP_V09, 1, DEEP),
	PAD_CFG_GPO(GPP_V10, 1, DEEP),
	PAD_CFG_GPO(GPP_V11, 1, DEEP),
	PAD_CFG_NF(GPP_V12, NONE, DEEP, NF1), // PCH_WAKE#
	_PAD_CFG_STRUCT(GPP_V13, 0x44000601, 0x0000),
	_PAD_CFG_STRUCT(GPP_V14, 0x44000601, 0x0000),
	_PAD_CFG_STRUCT(GPP_V15, 0x44000601, 0x0000),
	PAD_CFG_NF(GPP_V16, NONE, DEEP, NF1), // VCCST_EN
	PAD_CFG_GPO(GPP_V17, 1, DEEP),
};

void mainboard_configure_gpios(void)
{
	gpio_configure_pads(gpio_table, ARRAY_SIZE(gpio_table));
}
