/* SPDX-License-Identifier: GPL-2.0-only */

#include <bootstate.h>
#include <mainboard/gpio.h>
#include <soc/gpio.h>

static const struct pad_config gpio_table[] = {
	PAD_CFG_NF_IOSTANDBY_IGNORE(GPP_A00, UP_20K, DEEP, NF1), // ESPI_IO0_EC
	PAD_CFG_NF_IOSTANDBY_IGNORE(GPP_A01, UP_20K, DEEP, NF1), // ESPI_IO1_EC
	PAD_CFG_NF_IOSTANDBY_IGNORE(GPP_A02, UP_20K, DEEP, NF1), // ESPI_IO2_EC
	PAD_CFG_NF_IOSTANDBY_IGNORE(GPP_A03, UP_20K, DEEP, NF1), // ESPI_IO3_EC
	PAD_CFG_NF_IOSTANDBY_IGNORE(GPP_A04, UP_20K, DEEP, NF1), // ESPI_CS_EC#
	PAD_CFG_NF_IOSTANDBY_IGNORE(GPP_A05, DN_20K, DEEP, NF1), // ESPI_CLK_EC
	PAD_CFG_NF_IOSTANDBY_IGNORE(GPP_A06, NONE, DEEP, NF1), // ESPI_RESET#

	PAD_CFG_GPO(GPP_A08, 1, PLTRST), // SD_PWR_EN
	PAD_CFG_GPI(GPP_A09, NONE, PLTRST), // EXT 1K PU 1.8VA
	PAD_NC(GPP_A10, NONE),
	PAD_CFG_GPO(GPP_A11, 1, PLTRST), // WLAN_RST#
	PAD_NC(GPP_A12, NONE),
	PAD_NC(GPP_A13, NONE), // BODYSAR#
	PAD_CFG_GPO(GPP_A16, 1, DEEP), // PCH_BT_EN
	PAD_CFG_GPO(GPP_A17, 1, DEEP), // WIFI_RF_EN

	PAD_CFG_NF(GPP_B00, NONE, DEEP, NF1), // TBT_I2C_SCL
	PAD_CFG_NF(GPP_B01, NONE, DEEP, NF1), // TBT_I2C_SDA
	PAD_NC(GPP_B02, NONE),
	PAD_NC(GPP_B03, NONE),
	PAD_CFG_GPO(GPP_B04, 0, RSMRST), // Flash Descriptor Security Override strap
	PAD_NC(GPP_B05, NONE),
	PAD_CFG_GPO(GPP_B06, 1, DEEP), // ROM_I2C_EN
	PAD_NC(GPP_B07, NONE),
	PAD_NC(GPP_B08, NONE),
	//PAD_CFG_GPO(GPP_B09, 0, PLTRST), // M2_SSD1_RST#
	//PAD_CFG_GPO(GPP_B10, 1, PLTRST), // SSD1_PWR_EN
	PAD_CFG_GPI(GPP_B11, NONE, PLTRST),
	PAD_CFG_NF(GPP_B12, NONE, DEEP, NF1), // SLP_S0#
	PAD_CFG_NF(GPP_B13, NONE, DEEP, NF1), // PLT_RST#
	PAD_CFG_NF(GPP_B14, NONE, DEEP, NF2), // CPU_HDMI_HPD
	PAD_CFG_GPI(GPP_B15, NONE, PLTRST), // USB_OC3#
	PAD_NC(GPP_B16, NONE),
	PAD_NC(GPP_B17, NONE),
	PAD_NC(GPP_B18, NONE),
	PAD_NC(GPP_B19, NONE),
	PAD_NC(GPP_B20, NONE), // LTE_RST_N
	PAD_CFG_GPO(GPP_B21, 1, DEEP), // DG_FORCE_PWR
	PAD_NC(GPP_B22, NONE),
	PAD_CFG_GPO(GPP_B23, 0, RSMRST), // Reserved strap
	PAD_NC(GPP_B24, NONE),
	PAD_NC(GPP_B25, NONE),

	//PAD_CFG_GPI(GPP_C00, UP_20K, PLTRST), // BOARD_ID5
	//PAD_CFG_GPI(GPP_C01, UP_20K, PLTRST), // BOARD_ID6
	PAD_CFG_GPO(GPP_C02, 1, RSMRST), // TLS confidentiality strap
	PAD_CFG_NF(GPP_C03, NONE, DEEP, NF1), // SML0_CLK
	PAD_CFG_NF(GPP_C04, NONE, DEEP, NF1), // SML0_DATA
	PAD_CFG_GPO(GPP_C05, 0, RSMRST), // eSPI disable strap
	PAD_CFG_GPI(GPP_C06, NONE, PLTRST), // EXT 1K PU 1.8VA
	PAD_CFG_GPI(GPP_C07, NONE, PLTRST), // EXT 1K PU 1.8VA
	PAD_NC(GPP_C08, NONE),
	PAD_NC(GPP_C09, NONE),
	PAD_NC(GPP_C10, NONE),
	PAD_NC(GPP_C11, NONE),
	PAD_CFG_NF(GPP_C12, NONE, DEEP, NF1), // CARD_CLKREQ#_N
	PAD_CFG_NF(GPP_C13, NONE, DEEP, NF1), // WLAN_CLKREQ#_N
	PAD_NC(GPP_C14, NONE), // 5G_PCIE_CLKREQ#_N
	PAD_CFG_GPO(GPP_C15, 0, RSMRST), // Reserved strap
	PAD_CFG_NF(GPP_C16, NONE, DEEP, NF1), // TBTA_LSX0_TXD
	PAD_CFG_NF(GPP_C17, NONE, DEEP, NF1), // TBTA_LSX0_RXD
	PAD_NC(GPP_C18, NONE),
	PAD_NC(GPP_C19, NONE),
	PAD_NC(GPP_C20, NONE),
	PAD_NC(GPP_C21, NONE),
	PAD_CFG_NF(GPP_C22, NONE, DEEP, NF2), // HDMI_CTRLCLK
	PAD_CFG_NF(GPP_C23, NONE, DEEP, NF2), // HDMI_CTRLDATA

	PAD_CFG_GPO(GPP_D00, 1, DEEP), // SB_BLON
	PAD_NC(GPP_D01, NONE),
	PAD_NC(GPP_D02, NONE),
	PAD_NC(GPP_D03, NONE),
	PAD_NC(GPP_D04, NONE),
	PAD_NC(GPP_D05, NONE),
	PAD_NC(GPP_D06, NONE),
	PAD_NC(GPP_D07, NONE),
	PAD_NC(GPP_D08, NONE),
	PAD_NC(GPP_D09, NONE),
	PAD_CFG_NF(GPP_D10, NATIVE, DEEP, NF1), // HDA_BITCLK
	PAD_CFG_NF(GPP_D11, NATIVE, DEEP, NF1), // HDA_SYNC
	PAD_CFG_NF(GPP_D12, NATIVE, DEEP, NF1), // HDA_SDOUT / No Reboot strap
	PAD_CFG_NF(GPP_D13, NATIVE, DEEP, NF1), // HDA_SDIN0
	PAD_NC(GPP_D14, NONE),
	PAD_CFG_GPI(GPP_D15, NONE, DEEP), // CNVI_WAKE#
	PAD_CFG_NF(GPP_D16, NATIVE, DEEP, NF1), // HDA_RST#
	PAD_NC(GPP_D17, NONE),
	//PAD_CFG_NF(GPP_D18, NONE, DEEP, NF1), // SSD1_CLKREQ#_N
	PAD_CFG_GPO(GPP_D19, 1, PLTRST), // SD_PCIE_RST_N
	PAD_NC(GPP_D20, NONE),
	PAD_NC(GPP_D21, NONE),
	PAD_CFG_GPI(GPP_D22, NONE, PLTRST), // EXT 1K PU 1.8VA
	PAD_CFG_GPI(GPP_D23, NONE, PLTRST), // EXT 1K PU 1.8VA
	PAD_NC(GPP_D24, NONE),
	PAD_NC(GPP_D25, NONE),

	_PAD_CFG_STRUCT(GPP_E01, 0x42880100, 0x0000), // TPM_PIRQ#
	PAD_CFG_NF(GPP_E02, NONE, DEEP, NF2), // VRALERT#
	PAD_NC(GPP_E03, NONE),
	PAD_NC(GPP_E05, NONE),
	PAD_CFG_GPO(GPP_E06, 0, RSMRST), // JTAG ODT strap
	PAD_NC(GPP_E07, NONE),
	PAD_CFG_GPI(GPP_E08, NONE, DEEP), // WAKE_ON_WWAN_N
	PAD_CFG_GPI(GPP_E09, NONE, PLTRST), // USB_OC0#
	PAD_NC(GPP_E10, NONE),
	//PAD_CFG_GPI(GPP_E11, NONE, PLTRST), // BOARD_ID1
	PAD_CFG_NF(GPP_E12, NONE, DEEP, NF8), // AMP_SMB_CLK
	PAD_CFG_NF(GPP_E13, NONE, DEEP, NF8), // AMP_SMB_DATA
	//PAD_CFG_GPI(GPP_E14, NONE, PLTRST), // BOARD_ID2
	//PAD_CFG_GPI(GPP_E15, NONE, PLTRST), // BOARD_ID3
	PAD_NC(GPP_E16, NONE),
	//PAD_CFG_GPI(GPP_E17, NONE, PLTRST), // BOARD_ID4
	PAD_NC(GPP_E18, NONE),
	PAD_NC(GPP_E19, NONE),
	PAD_NC(GPP_E20, NONE),
	PAD_CFG_NF(GPP_E21, NONE, DEEP, NF1), // TBT_I2C_INT
	PAD_NC(GPP_E22, NONE),

	PAD_CFG_NF(GPP_F00, NONE, DEEP, NF1), // CNVI_BRI_DT
	PAD_CFG_NF(GPP_F01, UP_20K, DEEP, NF1), // CNVI_BRI_RSP
	PAD_CFG_NF(GPP_F02, NONE, DEEP, NF1), // CNVI_RGI_DT / M.2 CNVi mode strap
	PAD_CFG_NF(GPP_F03, UP_20K, DEEP, NF1), // CNVI_RGI_RSP
	PAD_CFG_NF(GPP_F04, NONE, DEEP, NF1), // CNVI_RST#
	PAD_CFG_NF(GPP_F05, NONE, DEEP, NF3), // CNVI_CLKREQ
	PAD_CFG_NF(GPP_F06, NONE, DEEP, NF1), // CNVI_GNSS_PA_BLANKING
	PAD_NC(GPP_F07, NONE),
	PAD_NC(GPP_F08, NONE),
	PAD_CFG_GPI(GPP_F09, NONE, DEEP), // TPM_DET
	PAD_NC(GPP_F10, NONE),
	PAD_NC(GPP_F11, NONE),
	PAD_CFG_NF(GPP_F12, NONE, DEEP, NF8), // I2C_SCL_TP
	PAD_CFG_NF(GPP_F13, NONE, DEEP, NF8), // I2C_SDA_TP
	PAD_NC(GPP_F14, NONE),
	PAD_NC(GPP_F15, NONE),
	PAD_CFG_GPO(GPP_F16, 1, PLTRST), // CCD_WP#
	PAD_NC(GPP_F17, NONE),
	PAD_CFG_GPI_APIC_LOW(GPP_F18, NONE, DEEP), // TP_ATTN#_N
	PAD_CFG_GPO(GPP_F19, 0, RSMRST), // Reserved strap
	PAD_NC(GPP_F20, NONE),
	PAD_NC(GPP_F22, NONE),
	PAD_NC(GPP_F23, NONE),

	PAD_CFG_GPO(GPP_H00, 0, RSMRST), // eSPI Flash Sharing strap (MAFS/SAFS)
	PAD_CFG_GPO(GPP_H01, 0, RSMRST), // Flash Descriptor Recovery strap
	PAD_CFG_GPO(GPP_H02, 0, RSMRST), // Reserved strap
	PAD_CFG_GPO(GPP_H03, 0, DEEP), // PCH_MUTE
	PAD_CFG_NF(GPP_H04, NONE, DEEP, NF2), // CNVI_MFUART2_RXD
	PAD_CFG_NF(GPP_H05, NONE, DEEP, NF2), // CNVI_MFUART2_TXD
	PAD_NC(GPP_H06, NONE),
	PAD_NC(GPP_H07, NONE),
	//PAD_CFG_NF(GPP_H08, NONE, DEEP, NF1), // UART_RX
	//PAD_CFG_NF(GPP_H09, NONE, DEEP, NF1), // UART_TX
	PAD_NC(GPP_H10, NONE),
	PAD_NC(GPP_H11, NONE),
	PAD_CFG_NF(GPP_H13, NONE, DEEP, NF1), // CPU_C10_GATE#
	PAD_NC(GPP_H14, NONE),
	PAD_NC(GPP_H15, NONE),
	PAD_NC(GPP_H16, NONE),
	PAD_NC(GPP_H17, NONE),
	PAD_NC(GPP_H19, NONE),
	PAD_NC(GPP_H20, NONE),
	PAD_CFG_NF(GPP_H21, NONE, DEEP, NF1), // PCH_I2C_SDA
	PAD_CFG_NF(GPP_H22, NONE, DEEP, NF1), // PCH_I2C_SCL

	PAD_NC(GPP_S00, NONE),
	PAD_NC(GPP_S01, NONE),
	PAD_NC(GPP_S02, NONE),
	PAD_NC(GPP_S03, NONE),
	PAD_NC(GPP_S04, NONE),
	PAD_NC(GPP_S05, NONE),
	PAD_NC(GPP_S06, NONE),
	PAD_NC(GPP_S07, NONE),

	PAD_CFG_NF(GPP_V00, NONE, DEEP, NF1), // PM_BATLOW#
	PAD_CFG_NF(GPP_V01, NONE, DEEP, NF1), // AC_PRESENT
	PAD_CFG_NF(GPP_V02, NONE, DEEP, NF1), // SOC_WAKE#
	PAD_CFG_NF(GPP_V03, NONE, DEEP, NF1), // CPU_PWR_BTN#
	PAD_CFG_NF(GPP_V04, NONE, DEEP, NF1), // SUSB#_PCH
	PAD_CFG_NF(GPP_V05, NONE, DEEP, NF1), // SUSC#_PCH
	PAD_CFG_NF(GPP_V06, NONE, DEEP, NF1), // SLP_A#
	PAD_CFG_NF(GPP_V07, NONE, DEEP, NF1), // SUS_CLK
	PAD_NC(GPP_V08, NONE),
	PAD_NC(GPP_V09, NONE),
	PAD_NC(GPP_V10, NONE),
	PAD_NC(GPP_V11, NONE),
	PAD_CFG_NF(GPP_V12, NONE, DEEP, NF1), // PCH_WAKE#
	PAD_CFG_NF(GPP_V16, NONE, DEEP, NF1), // VCCST_EN
	PAD_CFG_GPO(GPP_V17, 1, DEEP),
};

void mainboard_configure_gpios(void)
{
	gpio_configure_pads(gpio_table, ARRAY_SIZE(gpio_table));
}

static const struct pad_config nvme_pwr_seq2[] = {
	PAD_CFG_GPO(GPP_B10, 1, PLTRST), // SSD1_PWR_EN
	PAD_CFG_NF(GPP_D18, NONE, DEEP, NF1), // SSD1_CLKREQ#_N
};

static void nvme_enable_power(void *unused)
{
	gpio_configure_pads(nvme_pwr_seq2, ARRAY_SIZE(nvme_pwr_seq2));
}

BOOT_STATE_INIT_ENTRY(BS_PRE_DEVICE, BS_ON_EXIT, nvme_enable_power, NULL);

static const struct pad_config nvme_pwr_seq3[] = {
	PAD_CFG_GPO(GPP_B09, 1, PLTRST), // M2_SSD1_RST#
};

static void nvme_deassert_perst(void *unused)
{
	gpio_configure_pads(nvme_pwr_seq3, ARRAY_SIZE(nvme_pwr_seq3));
}

BOOT_STATE_INIT_ENTRY(BS_DEV_INIT_CHIPS, BS_ON_ENTRY, nvme_deassert_perst, NULL);
