/* SPDX-License-Identifier: GPL-2.0-only */

#include <mainboard/gpio.h>
#include <soc/gpio.h>

static const struct pad_config gpio_table[] = {
	PAD_CFG_NF(GPP_A00, UP_20K, DEEP, NF1), // ESPI_IO0_EC
	PAD_CFG_NF(GPP_A01, UP_20K, DEEP, NF1), // ESPI_IO1_EC
	PAD_CFG_NF(GPP_A02, UP_20K, DEEP, NF1), // ESPI_IO2_EC
	PAD_CFG_NF(GPP_A03, UP_20K, DEEP, NF1), // ESPI_IO3_EC
	PAD_CFG_NF(GPP_A04, UP_20K, DEEP, NF1), // ESPI_CS_EC#
	PAD_CFG_NF(GPP_A05, UP_20K, DEEP, NF1), // ESPI_CLK_EC
	PAD_CFG_NF(GPP_A06, NONE, DEEP, NF1), // ESPI_RESET#
	PAD_NC(GPP_A07, NONE),
	PAD_NC(GPP_A08, NONE),
	PAD_NC(GPP_A09, NONE),
	PAD_NC(GPP_A10, NONE),
	PAD_CFG_GPO(GPP_A11, 0, PLTRST),
	PAD_NC(GPP_A12, NONE),
	PAD_CFG_TERM_GPO(GPP_A13, 1, UP_20K, PLTRST),
	PAD_CFG_TERM_GPO(GPP_A14, 0, UP_20K, PLTRST),
	PAD_CFG_TERM_GPO(GPP_A15, 0, UP_20K, PLTRST),
	PAD_CFG_NF(GPP_A16, UP_20K, DEEP, NF1),
	PAD_CFG_GPI_INT(GPP_A17, NONE, PLTRST, LEVEL), // TP_ATTN#
	PAD_CFG_TERM_GPO(GPP_A18, 0, UP_20K, PLTRST),
	PAD_CFG_TERM_GPO(GPP_A19, 0, UP_20K, DEEP),
	PAD_CFG_TERM_GPO(GPP_A20, 0, NATIVE, DEEP),
	PAD_CFG_NF(GPP_A21, NATIVE, DEEP, NF1),
	_PAD_CFG_STRUCT(GPP_B00, 0x40100100, 0x0000),
	PAD_CFG_GPO(GPP_B01, 0, PLTRST),
	PAD_CFG_GPO(GPP_B02, 0, PLTRST),
	PAD_CFG_GPO(GPP_B03, 0, PLTRST),
	PAD_CFG_GPO(GPP_B04, 0, PLTRST),
	PAD_CFG_GPO(GPP_B05, 1, PLTRST),
	PAD_CFG_GPO(GPP_B06, 0, DEEP),
	PAD_CFG_GPO(GPP_B07, 1, DEEP),
	PAD_CFG_GPO(GPP_B08, 1, DEEP),
	PAD_CFG_GPI(GPP_B09, NONE, DEEP),
	PAD_CFG_GPI(GPP_B10, NONE, DEEP),
	PAD_CFG_NF(GPP_B11, NONE, DEEP, NF2), // CPU_HDMI_HPD
	PAD_CFG_NF(GPP_B12, NONE, DEEP, NF1),
	PAD_CFG_NF(GPP_B13, NONE, PLTRST, NF1),
	PAD_CFG_GPO(GPP_B14, 0, PLTRST),
	PAD_CFG_GPI(GPP_B15, NONE, DEEP),
	PAD_CFG_GPI(GPP_B16, NONE, DEEP),
	PAD_CFG_GPO(GPP_B17, 1, PLTRST), // HDMI_EN
	PAD_CFG_GPO(GPP_B18, 1, PLTRST),
	PAD_CFG_GPO(GPP_B19, 1, PLTRST),
	PAD_CFG_GPO(GPP_B20, 1, PLTRST),
	PAD_CFG_GPO(GPP_B21, 0, PLTRST),
	PAD_CFG_GPI(GPP_B22, NONE, DEEP),
	PAD_CFG_GPO(GPP_B23, 1, DEEP),
	PAD_CFG_NF(GPP_C00, NONE, DEEP, NF1), // SMB_CLK_DDR
	PAD_CFG_NF(GPP_C01, NONE, DEEP, NF1), // SMB_DATA_DDR
	PAD_CFG_NF(GPP_C02, NONE, DEEP, NF1), // GPP_C2_STRAP
	PAD_CFG_NF(GPP_C03, UP_20K, DEEP, NF1), // SML0_CLK
	PAD_CFG_NF(GPP_C04, UP_20K, DEEP, NF1), // SML0_DATA
	PAD_CFG_NF(GPP_C05, UP_20K, DEEP, NF1), // GPP_C5_STRAP
	PAD_CFG_NF(GPP_C06, UP_20K, DEEP, NF1), // TBT_I2C_SCL
	PAD_CFG_NF(GPP_C07, UP_20K, DEEP, NF1), // TBT_I2C_SDA
	PAD_CFG_NF(GPP_C08, NONE, DEEP, NF1), // GPP_C08_TEST
	PAD_CFG_NF(GPP_C09, NONE, DEEP, NF1), // CARD_CLKREQ
	PAD_CFG_GPO(GPP_C10, 0, PLTRST), // 5G_PCIE_CLKREQ
	PAD_CFG_NF(GPP_C11, NONE, PWROK, NF1), // WLAN_CLKREQ
	PAD_CFG_NF(GPP_C12, NONE, PWROK, NF1), // GPP_C13-TEST (typo from schematic)
	PAD_CFG_GPO(GPP_C13, 1, DEEP),
	PAD_CFG_NF(GPP_C14, NONE, DEEP, NF1),
	PAD_CFG_NF(GPP_C15, NONE, DEEP, NF1), // GPP_C15
	// GPP_C16 (TBTA_LSX0_TXD) configured by FSP
	// GPP_C17 (TBTA_LSX0_RXD) configured by FSP
	// GPP_C18 not connected
	// GPP_C19 not connected
	PAD_CFG_NF(GPP_C20, NONE, DEEP, NF2), // HDMI_CTRLCLK
	PAD_CFG_NF(GPP_C21, NONE, DEEP, NF2), // HDMI_CTRLDATA
	// GPP_C22 not connected
	// GPP_C23 not connected
	PAD_CFG_GPO(GPP_D00, 1, PLTRST),
	PAD_CFG_GPO(GPP_D01, 1, PLTRST),
	PAD_CFG_GPO(GPP_D02, 1, PLTRST),
	PAD_NC(GPP_D03, NONE),
	PAD_CFG_GPO(GPP_D04, 0, PLTRST),
	PAD_CFG_GPO(GPP_D05, 1, PLTRST),
	PAD_CFG_GPO(GPP_D06, 0, PLTRST),
	PAD_CFG_GPO(GPP_D07, 0, PLTRST),
	PAD_CFG_GPO(GPP_D08, 0, PLTRST),
	PAD_CFG_GPO(GPP_D09, 0, PLTRST),
	PAD_CFG_NF(GPP_D10, NONE, DEEP, NF1),
	PAD_CFG_NF(GPP_D11, NATIVE, DEEP, NF1),
	PAD_CFG_NF(GPP_D12, NATIVE, DEEP, NF1),
	PAD_CFG_NF(GPP_D13, NATIVE, DEEP, NF1),
	PAD_CFG_GPO(GPP_D14, 0, PLTRST),
	PAD_CFG_GPO(GPP_D15, 0, PLTRST),
	PAD_CFG_GPO(GPP_D16, 0, DEEP),
	PAD_CFG_NF(GPP_D17, NONE, DEEP, NF1),
	PAD_NC(GPP_D18, NONE), // GPP_D18-TEST
	PAD_CFG_NF(GPP_D19, NONE, DEEP, NF1), // SSD2_CLKREQ
	PAD_CFG_NF(GPP_D20, NONE, DEEP, NF1), // SSD1_CLKREQ
	PAD_CFG_NF(GPP_D21, NONE, DEEP, NF1),
	PAD_CFG_NF(GPP_D22, NATIVE, DEEP, NF1),
	PAD_CFG_NF(GPP_D23, NATIVE, DEEP, NF1),
	PAD_CFG_GPO(GPP_E00, 0, PLTRST),
	_PAD_CFG_STRUCT(GPP_E01, 0x40100100, 0x1000),
	PAD_CFG_GPI(GPP_E02, NONE, DEEP),
	PAD_NC(GPP_E03, NONE),
	PAD_CFG_GPO(GPP_E04, 0, PLTRST),
	PAD_CFG_GPO(GPP_E05, 0, PLTRST),
	PAD_CFG_GPI(GPP_E06, NONE, DEEP),
	PAD_CFG_GPO(GPP_E07, 0, PLTRST),
	PAD_CFG_GPO(GPP_E08, 0, PLTRST),
	PAD_CFG_GPI(GPP_E09, NONE, DEEP),
	PAD_CFG_GPO(GPP_E10, 0, PLTRST),
	PAD_CFG_GPI(GPP_E11, NONE, DEEP),
	_PAD_CFG_STRUCT(GPP_E12, 0x84002200, 0x0000),
	_PAD_CFG_STRUCT(GPP_E13, 0x44002100, 0x0000),
	PAD_CFG_NF(GPP_E14, NONE, DEEP, NF1),
	PAD_CFG_GPO(GPP_E15, 0, PLTRST),
	PAD_CFG_NF(GPP_E16, NONE, DEEP, NF2),
	PAD_CFG_GPO(GPP_E17, 0, PLTRST),
	PAD_NC(GPP_E18, NONE),
	PAD_NC(GPP_E19, NONE),
	PAD_NC(GPP_E20, NONE),
	PAD_NC(GPP_E21, NONE),
	PAD_CFG_TERM_GPO(GPP_E22, 0, DN_20K, PLTRST),
	PAD_CFG_NF(GPP_F00, NONE, DEEP, NF1),
	PAD_CFG_NF(GPP_F01, UP_20K, DEEP, NF1),
	PAD_CFG_NF(GPP_F02, NONE, DEEP, NF1),
	PAD_CFG_NF(GPP_F03, UP_20K, DEEP, NF1),
	PAD_CFG_NF(GPP_F04, NONE, DEEP, NF1),
	PAD_CFG_NF(GPP_F05, NONE, DEEP, NF3),
	PAD_CFG_NF(GPP_F06, NONE, DEEP, NF1),
	PAD_CFG_NF(GPP_F07, DN_20K, DEEP, NF1),
	PAD_CFG_NF(GPP_F08, DN_20K, DEEP, NF1),
	PAD_CFG_GPI(GPP_F09, NONE, DEEP),
	PAD_NC(GPP_F10, NONE),
	PAD_CFG_GPO(GPP_F11, 0, PLTRST),
	_PAD_CFG_STRUCT(GPP_F12, 0x44002300, 0x0000), // AMP_SMB_CLK
	_PAD_CFG_STRUCT(GPP_F13, 0x44002300, 0x0000), // AMP_SMB_DATA
	PAD_CFG_GPO(GPP_F14, 0, PLTRST),
	PAD_CFG_GPO(GPP_F15, 0, PLTRST),
	PAD_CFG_GPO(GPP_F16, 0, PLTRST),
	PAD_CFG_GPO(GPP_F17, 0, PLTRST),
	PAD_CFG_GPO(GPP_F18, 0, DEEP),
	PAD_CFG_GPO(GPP_F19, 0, PLTRST),
	PAD_CFG_GPO(GPP_F20, 0, PLTRST),
	PAD_CFG_GPO(GPP_F21, 0, PLTRST),
	PAD_CFG_GPO(GPP_F22, 0, PLTRST),
	PAD_CFG_GPO(GPP_F23, 0, PLTRST),
	PAD_CFG_GPO(GPP_H00, 0, PLTRST),
	PAD_CFG_GPO(GPP_H01, 0, PLTRST),
	PAD_CFG_GPO(GPP_H02, 1, PLTRST),
	PAD_NC(GPP_H03, NONE),
	PAD_NC(GPP_H04, NONE),
	PAD_NC(GPP_H05, NONE),
	PAD_NC(GPP_H06, NONE),
	PAD_NC(GPP_H07, NONE),
	PAD_NC(GPP_H08, NONE),
	PAD_NC(GPP_H09, NONE),
	PAD_CFG_GPO(GPP_H10, 0, PLTRST),
	PAD_CFG_GPO(GPP_H11, 0, PLTRST),
	PAD_NC(GPP_H12, NONE),
	PAD_CFG_NF(GPP_H13, NONE, DEEP, NF1),
	PAD_CFG_GPO(GPP_H14, 0, PLTRST),
	PAD_CFG_GPO(GPP_H15, 0, PLTRST),
	PAD_CFG_GPO(GPP_H16, 0, PLTRST),
	PAD_CFG_GPO(GPP_H17, 0, PLTRST),
	PAD_NC(GPP_H18, NONE),
	PAD_CFG_NF(GPP_H19, NONE, DEEP, NF1),
	PAD_CFG_NF(GPP_H20, NONE, DEEP, NF1),
	PAD_CFG_NF(GPP_H21, NONE, DEEP, NF1),
	PAD_CFG_NF(GPP_H22, NONE, DEEP, NF1),
	PAD_CFG_GPO(GPP_S00, 0, PLTRST),
	PAD_CFG_GPO(GPP_S01, 0, PLTRST),
	PAD_CFG_GPO(GPP_S02, 0, PLTRST),
	PAD_CFG_GPO(GPP_S03, 0, PLTRST),
	PAD_CFG_GPO(GPP_S04, 0, PLTRST),
	PAD_CFG_GPO(GPP_S05, 0, PLTRST),
	PAD_CFG_NF(GPP_S06, NONE, DEEP, NF3),
	PAD_CFG_NF(GPP_S07, NONE, DEEP, NF3),
	PAD_CFG_NF(GPP_V00, NONE, DEEP, NF1),
	PAD_CFG_NF(GPP_V01, NONE, DEEP, NF1),
	PAD_CFG_NF(GPP_V02, NONE, DEEP, NF1),
	PAD_CFG_NF(GPP_V03, NONE, DEEP, NF1),
	PAD_CFG_NF(GPP_V04, NONE, DEEP, NF1),
	PAD_CFG_NF(GPP_V05, UP_20K, DEEP, NF1),
	PAD_CFG_NF(GPP_V06, NATIVE, DEEP, NF1),
	PAD_CFG_GPI(GPP_V07, NATIVE, DEEP),
	PAD_CFG_NF(GPP_V08, NONE, DEEP, NF1),
	PAD_CFG_NF(GPP_V09, NONE, DEEP, NF1),
	PAD_CFG_NF(GPP_V10, NONE, DEEP, NF1),
	PAD_CFG_NF(GPP_V11, NONE, DEEP, NF1),
	PAD_NC(GPP_V12, NONE),
	PAD_CFG_NF(GPP_V13, NONE, DEEP, NF1),
	PAD_CFG_NF(GPP_V14, NONE, DEEP, NF1),
	PAD_CFG_NF(GPP_V15, NONE, PLTRST, NF1),
	PAD_CFG_GPO(GPP_V16, 0, PLTRST),
	PAD_CFG_GPO(GPP_V17, 0, PLTRST),
	PAD_NC(GPP_V18, NONE),
	PAD_CFG_NF(GPP_V19, NONE, DEEP, NF1),
	PAD_NC(GPP_V20, NONE),
	PAD_NC(GPP_V21, NONE),
	PAD_NC(GPP_V22, NONE),
	PAD_NC(GPP_V23, NONE),
};

void mainboard_configure_gpios(void)
{
	gpio_configure_pads(gpio_table, ARRAY_SIZE(gpio_table));
}
