/* SPDX-License-Identifier: GPL-2.0-only */

#ifndef _SOC_QUALCOMM_X1P42100_LPASS_H_
#define _SOC_QUALCOMM_X1P42100_LPASS_H_

#include <soc/addressmap.h>
#include <types.h>

/* LPASS AON CC PLL Settings */
#define HAL_CLK_LPASS_AON_CC_PLL_L_VALUE	0x00000020
#define HAL_CLK_LPASS_AON_CC_PLL_ALPHA_VALUE	0x00000000
#define HAL_CLK_LPASS_AON_CC_PLL_RING_CAL_L_VALUE	(0x44 << 16)
#define HAL_CLK_LPASS_AON_CC_PLL_PROC_CAL_L_VALUE	(0x44 << 24)
#define HAL_CLK_LPASS_AON_CC_PLL_CONFIG_CTL	0x20485699
#define HAL_CLK_LPASS_AON_CC_PLL_CONFIG_CTL_U	0x00182261
#define HAL_CLK_LPASS_AON_CC_PLL_CONFIG_CTL_U1	0x82AA299C
#define HAL_CLK_LPASS_AON_CC_PLL_TEST_CTL	0x00000000
#define HAL_CLK_LPASS_AON_CC_PLL_TEST_CTL_U	0x00000003
#define HAL_CLK_LPASS_AON_CC_PLL_TEST_CTL_U1	0x00009000
#define HAL_CLK_LPASS_AON_CC_PLL_TEST_CTL_U2	0x00000034
#define HAL_CLK_LPASS_AON_CC_PLL_USER_CTL	0x00E00041
#define HAL_CLK_LPASS_AON_CC_PLL_USER_CTL_U	0x00000105

enum lpass_voltage_level {
	LPASS_VOLTAGE_LOWSVS_D1,
	LPASS_VOLTAGE_LOWSVS,
	LPASS_VOLTAGE_SVS,
	LPASS_VOLTAGE_SVS_L1,
	LPASS_VOLTAGE_NOMINAL,
	LPASS_VOLTAGE_TURBO,
	LPASS_VOLTAGE_MAX
};

/* Default voltage level for boot */
#define LPASS_DEFAULT_VOLTAGE_LEVEL	LPASS_VOLTAGE_SVS_L1

/* LPASS QDSP6SS PLL user control bit shifts */
#define QDSP6SS_PLL_PLLOUT_MAIN_SHFT	0

/* LPASS QDSP6SS PLL Settings - Voltage-dependent values */
#define HAL_CLK_LPASS_QDSP6SS_PLL_L_VALUE_LOWSVS_D1		0x00000018
#define HAL_CLK_LPASS_QDSP6SS_PLL_ALPHA_VALUE_LOWSVS_D1	0x00000000

#define HAL_CLK_LPASS_QDSP6SS_PLL_L_VALUE_LOWSVS		0x0000001F
#define HAL_CLK_LPASS_QDSP6SS_PLL_ALPHA_VALUE_LOWSVS		0x00000000

#define HAL_CLK_LPASS_QDSP6SS_PLL_L_VALUE_SVS			0x00000029
#define HAL_CLK_LPASS_QDSP6SS_PLL_ALPHA_VALUE_SVS		0x00000000

#define HAL_CLK_LPASS_QDSP6SS_PLL_L_VALUE_SVS_L1		0x00000032
#define HAL_CLK_LPASS_QDSP6SS_PLL_ALPHA_VALUE_SVS_L1		0x00000000

#define HAL_CLK_LPASS_QDSP6SS_PLL_L_VALUE_NOMINAL		0x0000003E
#define HAL_CLK_LPASS_QDSP6SS_PLL_ALPHA_VALUE_NOMINAL		0x00000000

#define HAL_CLK_LPASS_QDSP6SS_PLL_L_VALUE_TURBO		0x0000004E
#define HAL_CLK_LPASS_QDSP6SS_PLL_ALPHA_VALUE_TURBO		0x00000000

#define HAL_CLK_LPASS_QDSP6SS_PLL_L_VALUE	HAL_CLK_LPASS_QDSP6SS_PLL_L_VALUE_SVS_L1
#define HAL_CLK_LPASS_QDSP6SS_PLL_ALPHA_VALUE	HAL_CLK_LPASS_QDSP6SS_PLL_ALPHA_VALUE_SVS_L1
#define HAL_CLK_LPASS_QDSP6SS_PLL_CAL_L_VALUE	0x00000044
#define HAL_CLK_LPASS_QDSP6SS_PLL_CONFIG_CTL	0x20485699
#define HAL_CLK_LPASS_QDSP6SS_PLL_CONFIG_CTL_U	0x00182261
#define HAL_CLK_LPASS_QDSP6SS_PLL_CONFIG_CTL_U1	0x82AA299C
#define HAL_CLK_LPASS_QDSP6SS_PLL_TEST_CTL	0x00000000
#define HAL_CLK_LPASS_QDSP6SS_PLL_TEST_CTL_U	0x00000003
#define HAL_CLK_LPASS_QDSP6SS_PLL_TEST_CTL_U1	0x00009000
#define HAL_CLK_LPASS_QDSP6SS_PLL_TEST_CTL_U2	0x00000034
#define HAL_CLK_LPASS_QDSP6SS_PLL_USER_CTL	0x00000000
#define HAL_CLK_LPASS_QDSP6SS_PLL_USER_CTL_U	0x00000005

#define LPASS_CORE_HM_READY			(1 << 0)
#define HW_CTL					(1 << 1)
#define GDSC_ENABLE_BIT				0
#define GDSC_RETAIN_FF_ENABLE			(1 << 11)

#define LPASS_CORE_HM_VOTE_POWER_ON		0x0
#define GDSC_PWR_ON				BIT(31)
#define LPASS_CORE_HM_VOTE_POWER_DOWN		0x1
#define BCM_LP0_VOTE_VALUE			0x60004001

/* NanoRCG status bits */
#define LPASS_NANO_RCG_PORT2			(1 << 2)

/* Low power handshake bits */
#define LPASS_LP_HANDSHAKE_ACK			(1 << 0)  /* Bit 0: ACK status (RO) */
#define LPASS_LP_HANDSHAKE_ACTIVE		(1 << 1)  /* Bit 1: ACTIVE status (RO) */
#define LPASS_LP_HANDSHAKE_REQUEST		(1 << 2)  /* Bit 2: REQUEST control (RW) */

/* NTS debug bridge handshake tuning */
#define LPASS_NTS_HANDSHAKE_TIMEOUT_US		500000
#define LPASS_NTS_HANDSHAKE_DELAY_US		100

/* Q6 Core RCG configuration */
#define Q6_CORE_RCG_CFG				0x201
#define CLK_CTL_CMD_UPDATE_SHFT			0
#define LPASS_RCG_UPDATE_TIMEOUT_US		100000

/* RSC wait event override mask */
#define LPASS_RSC_WAIT_EVENT_MASK		0x8

/* CR QCTDD10442361 workaround - NOC island isolation bits */
#define CHIP_CX_RSCC_BYPASS_EN			(1 << 21)
#define AON_NOC_STALL_MASK			(1 << 22)
#define CHIPCX_SBM_FAULTINEN0_PORT0		(1 << 0)

/* TCM (Tightly Coupled Memory) control bits */
#define LPASS_TCM_MAX_BLOCKS			9

/* Q6 Boot control bits */
#define BOOT_CORE_START				(1 << 0)
#define BOOT_FSM_START				(1 << 0)
#define LPASS_BOOT_FSM_TIMEOUT_US		1000000

#define TCSR_BOOT_IMEM_DISABLE_OFF	0x013300
#define TCSR_BOOT_IMEM_DISABLE		((void *)(TCSR_BASE + TCSR_BOOT_IMEM_DISABLE_OFF))

enum cb_err lpass_bring_up(void);

/*
 * Clock workarounds for LPASS clocks.
 *
 * Keep these lists declarative (CBCR pointers only); apply behavior in
 * lpass_apply_clock_workarounds().
 */
struct lpass_cbcr_list {
	uint32_t *cbcr;
};

#endif /* _SOC_QUALCOMM_X1P42100_LPASS_H_ */
