/* SPDX-License-Identifier: GPL-2.0-only */

#ifndef MAINBOARD_GPIO_H
#define MAINBOARD_GPIO_H

#define DGPU_RST_N GPP_F8
#define DGPU_PWR_EN GPP_F9
#define DGPU_GC6 GPP_K11

#ifndef __ACPI__

#include <soc/gpe.h>
#include <soc/gpio.h>

/* Pad configuration in romstage. */
static const struct pad_config early_gpio_table[] = {
	PAD_CFG_GPI(GPP_C20, NONE, DEEP), // UART2_RXD
	PAD_CFG_GPI(GPP_C21, NONE, DEEP), // UART2_TXD
	PAD_CFG_NF(GPP_F19, NONE, DEEP, NF1), // NB_ENAVDD
	PAD_CFG_TERM_GPO(DGPU_RST_N, 0, NONE, DEEP), // DGPU_RST#_PCH
	PAD_CFG_TERM_GPO(DGPU_PWR_EN, 0, NONE, DEEP), // DGPU_PWR_EN
};

/* Pad configuration in ramstage. */
static const struct pad_config gpio_table[] = {
	// BATLOW#
	PAD_CFG_NF(GPD0, UP_20K, PWROK, NF1),
	// AC_PRESENT
	PAD_CFG_NF(GPD1, NATIVE, PWROK, NF1),
	// LAN_WAKE#
	PAD_CFG_GPI(GPD2, NATIVE, PWROK),
	// PWR_BTN#
	PAD_CFG_NF(GPD3, UP_20K, PWROK, NF1),
	// SUSB#_PCH
	PAD_CFG_NF(GPD4, NONE, PWROK, NF1),
	// SUSC#_PCH
	PAD_CFG_NF(GPD5, NONE, PWROK, NF1),
	// SLP_A#
	PAD_CFG_NF(GPD6, NONE, PWROK, NF1),
	// GPD7
	PAD_CFG_GPI(GPD7, NONE, PWROK),
	// SUS_CLK
	PAD_CFG_NF(GPD8, NONE, PWROK, NF1),
	// PCH_SLP_WLAN#
	PAD_CFG_GPO(GPD9, 0, PWROK),
	// SLP_S5#
	PAD_CFG_NF(GPD10, NONE, PWROK, NF1),
	// LAN_DISABLE#
	PAD_CFG_GPI(GPD11, NONE, PWROK),
	// Test point
	_PAD_CFG_STRUCT(GPD12, 0x04000300, 0x0000),
	// ESPI_AD0
	PAD_CFG_NF(GPP_A0, UP_20K, DEEP, NF1),
	// ESPI_AD1
	PAD_CFG_NF(GPP_A1, UP_20K, DEEP, NF1),
	// ESPI_AD2
	PAD_CFG_NF(GPP_A2, UP_20K, DEEP, NF1),
	// ESPI_AD3
	PAD_CFG_NF(GPP_A3, UP_20K, DEEP, NF1),
	// ESPI_FRAME#
	PAD_CFG_NF(GPP_A4, UP_20K, DEEP, NF1),
	// ESPI_KBC
	PAD_CFG_NF(GPP_A5, DN_20K, DEEP, NF1),
	// ESPI_RESET_N
	PAD_CFG_NF(GPP_A6, NONE, DEEP, NF1),
	// GPP_A7
	PAD_CFG_GPI(GPP_A7, UP_20K, DEEP),
	// GPP_A8
	PAD_CFG_GPI(GPP_A8, UP_20K, DEEP),
	// GPP_A9
	PAD_CFG_GPI(GPP_A9, UP_20K, DEEP),
	// SERIRQ
	PAD_CFG_GPI(GPP_A10, UP_20K, DEEP),
	// NC
	PAD_CFG_GPI(GPP_A11, UP_20K, DEEP),
	// NC
	PAD_CFG_GPI(GPP_A12, UP_20K, DEEP),
	// NC
	PAD_CFG_GPI(GPP_A13, UP_20K, DEEP),
	// PM_CLKRUN#
	PAD_CFG_GPI(GPP_A14, NONE, DEEP),
	// TPM_PIRQ#
	_PAD_CFG_STRUCT(GPP_B0, 0x40100100, 0x3000),
	// GPP_B1
	PAD_CFG_GPI(GPP_B1, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_B2, NONE, DEEP),
	// BT_EN_PCH
	PAD_CFG_GPO(GPP_B3, 1, DEEP),
	// NC
	PAD_CFG_GPI(GPP_B4, NONE, DEEP),
	// GFX_CLKREQ0#
	PAD_CFG_NF(GPP_B5, NONE, DEEP, NF1),
	// NC
	PAD_CFG_GPI(GPP_B6, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_B7, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_B8, NONE, DEEP),
	// SSD2_CLKREQ4#
	PAD_CFG_NF(GPP_B9, NONE, DEEP, NF1),
	// LAN_CLKREQ5#
	PAD_CFG_NF(GPP_B10, NONE, DEEP, NF1),
	// NC
	PAD_CFG_GPI(GPP_B11, NONE, DEEP),
	// SLP_S0#
	PAD_CFG_NF(GPP_B12, NONE, DEEP, NF1),
	// PLT_RST#
	PAD_CFG_NF(GPP_B13, NONE, DEEP, NF1),
	// PCH_SPKR
	PAD_CFG_NF(GPP_B14, NONE, DEEP, NF1),
	// SSD_PWR_EN#
	PAD_CFG_GPO(GPP_B15, 1, DEEP),
	// NC
	PAD_CFG_GPI(GPP_B16, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_B17, NONE, DEEP),
	// GSPI0_MOSI
	PAD_CFG_GPI(GPP_B18, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_B19, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_B20, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_B21, NONE, DEEP),
	// GSPI1_MOSI
	PAD_CFG_GPI(GPP_B22, NONE, DEEP),
	// SML1_ALERT#
	PAD_CFG_GPI(GPP_B23, NONE, DEEP),
	// SMB_CLK
	PAD_CFG_NF(GPP_C0, NONE, DEEP, NF1),
	// SMB_DAT
	PAD_CFG_NF(GPP_C1, NONE, DEEP, NF1),
	// CNVI_WAKE#
	PAD_CFG_GPI(GPP_C2, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_C3, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_C4, NONE, DEEP),
	// SML0_ALERT#
	PAD_CFG_GPI(GPP_C5, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_C6, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_C7, NONE, DEEP),
	// TPM_DET
	PAD_CFG_GPI(GPP_C8, NONE, DEEP),
	// BOARD_ID1
	PAD_CFG_GPI(GPP_C9, NONE, DEEP),
	// BOARD_ID2
	PAD_CFG_GPI(GPP_C10, NONE, DEEP),
	// BOARD_ID3
	PAD_CFG_GPI(GPP_C11, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_C12, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_C13, NONE, DEEP),
	// GPC14_RTD3
	PAD_CFG_GPI(GPP_C14, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_C15, NONE, DEEP),
	// I2C_SDA_TP
	PAD_CFG_NF(GPP_C16, NONE, PWROK, NF1),
	// I2C_SCL_TP
	PAD_CFG_NF(GPP_C17, NONE, PWROK, NF1),
	// SCI#
	PAD_CFG_GPI(GPP_C18, NONE, DEEP),
	// SWI#
	PAD_CFG_GPI(GPP_C19, NONE, DEEP),
	/* Configured in early_gpio_table
	 * // UART2_RXD
	 * PAD_CFG_GPI(GPP_C20, NONE, DEEP),
	 * // UART2_TXD
	 * PAD_CFG_GPI(GPP_C21, NONE, DEEP),
	 */
	// UART2_RTS#
	PAD_CFG_GPO(GPP_C22, 1, DEEP),
	// SMI#
	PAD_CFG_GPI(GPP_C23, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_D0, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_D1, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_D2, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_D3, NONE, DEEP),
	// SML1_CLK
	PAD_CFG_NF(GPP_D4, NONE, DEEP, NF1),
	// CNVI_RF_RST#
	PAD_CFG_NF(GPP_D5, NONE, DEEP, NF2),
	// XTAL_CLKREQ
	PAD_CFG_NF(GPP_D6, NONE, DEEP, NF3),
	// NC
	PAD_CFG_GPI(GPP_D7, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_D8, NONE, DEEP),
	// SML0_CLK
	PAD_CFG_NF(GPP_D9, NONE, DEEP, NF1),
	// SML0_DATA
	PAD_CFG_NF(GPP_D10, NONE, DEEP, NF1),
	// NC
	PAD_CFG_GPI(GPP_D11, NATIVE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_D12, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_D13, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_D14, NONE, DEEP),
	// SML1_DATA
	PAD_CFG_NF(GPP_D15, NONE, DEEP, NF1),
	// NC
	PAD_CFG_GPI(GPP_D16, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_D17, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_D18, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_D19, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_D20, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_D21, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_D22, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_D23, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_E0, NONE, DEEP),
	// SATAGP1
	PAD_CFG_NF(GPP_E1, UP_20K, DEEP, NF1),
	// NC
	PAD_CFG_GPI(GPP_E2, NONE, DEEP),
	// SMI#
	PAD_CFG_GPI(GPP_E3, NONE, DEEP),
	// DEVSLP0
	PAD_CFG_GPI(GPP_E4, NONE, DEEP),
	// DEVSLP1
	PAD_CFG_NF(GPP_E5, NONE, PWROK, NF1),
	// PCH_MUTE#
	PAD_CFG_GPI(GPP_E6, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_E7, NONE, DEEP),
	// SATA_LED#
	PAD_CFG_NF(GPP_E8, NONE, DEEP, NF1),
	// USB_OC0#
	PAD_CFG_GPI(GPP_E9, NONE, DEEP),
	// USB_OC1#
	PAD_CFG_GPI(GPP_E10, NONE, DEEP),
	// USB_OC2#
	PAD_CFG_GPI(GPP_E11, NONE, DEEP),
	// USB_OC3#
	PAD_CFG_GPI(GPP_E12, NONE, DEEP),
	// SATAGP3
	PAD_CFG_NF(GPP_F0, NONE, DEEP, NF2),
	// SATAGP4
	PAD_CFG_GPI(GPP_F1, NONE, DEEP),
	// LAN_RTD3#
	PAD_CFG_GPO(GPP_F2, 1, PLTRST),
	// GPP_LAN_RST#
	PAD_CFG_GPO(GPP_F3, 1, DEEP),
	// SATA_PWR_EN
	PAD_CFG_GPO(GPP_F4, 1, DEEP),
	// 1P05_CTRL
	PAD_CFG_GPO(GPP_F5, 1, DEEP),
	// NC
	PAD_CFG_GPI(GPP_F6, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_F7, NONE, DEEP),
	/* GPU enabled or not in bootblock.c
	 * // DGPU_RST#_PCH
	 * PAD_CFG_GPO(GPP_F8, 1, DEEP),
	 * // DGPU_PWR_EN
	 * PAD_CFG_GPO(GPP_F9, 1, DEEP),
	 */
	// BIOS_REC
	PAD_CFG_GPI(GPP_F10, NONE, DEEP),
	// PCH_RSVD
	PAD_CFG_GPI(GPP_F11, NONE, DEEP),
	// PCH_WLAN_EN
	PAD_CFG_GPO(GPP_F12, 1, DEEP),
	// NC
	PAD_CFG_GPI(GPP_F13, NONE, DEEP),
	// PS_ON#
	PAD_CFG_GPI(GPP_F14, NONE, DEEP),
	// SKTOCC#
	PAD_CFG_GPI(GPP_F15, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_F16, NONE, DEEP),
	// SB_BLON
	PAD_CFG_GPO(GPP_F17, 1, DEEP),
	// NC
	PAD_CFG_GPI(GPP_F18, NONE, DEEP),
	// NB_ENAVDD
	PAD_CFG_NF(GPP_F19, NONE, DEEP, NF1),
	// BLON
	PAD_CFG_NF(GPP_F20, NONE, DEEP, NF1),
	// EDP_BRIGHTNESS
	PAD_CFG_NF(GPP_F21, NONE, DEEP, NF1),
	// VNN_CTRL
	PAD_NC(GPP_F22, NONE),
	// NC
	PAD_CFG_GPI(GPP_F23, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_G0, NONE, DEEP),
	// CNVI_DET#
	PAD_CFG_GPI(GPP_G1, NONE, DEEP),
	// Test Point
	PAD_CFG_GPI(GPP_G2, DN_20K, DEEP),
	// NC
	PAD_CFG_GPI(GPP_G3, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_G4, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_G5, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_G6, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_G7, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_G8, NATIVE, DEEP),
	// GPP_G9
	PAD_CFG_GPI(GPP_G9, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_G10, NATIVE, DEEP),
	// GPP_G11
	PAD_CFG_GPI(GPP_G11, NONE, DEEP),
	// NC
	_PAD_CFG_STRUCT(GPP_G12, 0x44001300, 0x3c00),
	// GPP_G13
	_PAD_CFG_STRUCT(GPP_G13, 0x44001300, 0x3c00),
	// PCH_MDP_CLK
	PAD_CFG_GPI(GPP_G14, NATIVE, DEEP),
	// PCH_MDP_DATA
	PAD_CFG_GPI(GPP_G15, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_H0, NONE, DEEP),
	// CARD_CLKREQ7#
	PAD_CFG_NF(GPP_H1, NONE, DEEP, NF1),
	// WLAN_CLKREQ8#
	PAD_CFG_NF(GPP_H2, NONE, DEEP, NF1),
	// SSD1_CLKREQ9#
	PAD_CFG_NF(GPP_H3, NONE, DEEP, NF1),
	// NC
	PAD_CFG_GPI(GPP_H4, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_H5, NONE, DEEP),
	// SB_KBCRST#
	PAD_CFG_GPI(GPP_H6, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_H7, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_H8, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_H9, NONE, DEEP),
	// SML_2CLK
	PAD_CFG_GPI(GPP_H10, NONE, DEEP),
	// SML_2DATA
	PAD_CFG_GPI(GPP_H11, NONE, DEEP),
	// SML_2ALERT#
	PAD_CFG_GPI(GPP_H12, NONE, DEEP),
	// SML_3CLK
	PAD_CFG_GPI(GPP_H13, NONE, DEEP),
	// SML_3DATA
	PAD_CFG_GPI(GPP_H14, NONE, DEEP),
	// SML_3ALERT#
	PAD_CFG_GPI(GPP_H15, NONE, PLTRST),
	// SML_4CLK
	PAD_CFG_GPI(GPP_H16, NONE, DEEP),
	// SSD2_PWR_EN#
	PAD_CFG_GPO(GPP_H17, 1, DEEP),
	// SML_4ALERT#
	PAD_CFG_GPI(GPP_H18, NONE, DEEP),
	// PCH_FLASH_I2C_SDA
	PAD_CFG_GPI(GPP_H19, NONE, DEEP),
	// PCH_FLASH_I2C_SCL
	PAD_CFG_GPI(GPP_H20, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_H21, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_H22, NONE, DEEP),
	// M2_SSD_RST#
	PAD_CFG_GPO(GPP_H23, 1, DEEP),
	// PMC_ALERT#
	PAD_CFG_NF(GPP_I0, NONE, PWROK, NF1),
	// GPU_EVENT#
	PAD_CFG_GPI(GPP_I1, NONE, DEEP),
	// GPP_I3 (sic)
	PAD_CFG_GPI(GPP_I2, NONE, DEEP),
	// GPP_I4 (sic)
	PAD_CFG_GPI(GPP_I3, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_I4, NONE, DEEP),
	// HDMI_CTRLCLK
	PAD_CFG_NF(GPP_I5, NONE, DEEP, NF1),
	// HDMI_CTRLDATA
	PAD_CFG_NF(GPP_I6, NONE, DEEP, NF1),
	// NC
	PAD_CFG_GPI(GPP_I7, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_I8, NONE, DEEP),
	// M2_SSD2_RST#
	PAD_CFG_GPO(GPP_I9, 1, DEEP),
	// NC
	PAD_CFG_GPI(GPP_I10, DN_20K, DEEP),
	// USB_OC4#
	PAD_CFG_GPI(GPP_I11, NONE, PLTRST),
	// USB_OC5#
	PAD_CFG_GPI(GPP_I12, NONE, PLTRST),
	// USB_OC6#
	PAD_CFG_GPI(GPP_I13, NONE, PLTRST),
	// USB_OC7#
	PAD_CFG_GPI(GPP_I14, NONE, PLTRST),
	// CNVI_GNSS_PA_BLANKING
	PAD_CFG_NF(GPP_J0, NONE, DEEP, NF1),
	// CPU_C10_GATE#
	PAD_CFG_NF(GPP_J1, NONE, DEEP, NF1),
	// CNVI_BRI_DT
	PAD_CFG_NF(GPP_J2, NONE, DEEP, NF1),
	// CNVI_BRI_RSP
	PAD_CFG_NF(GPP_J3, UP_20K, DEEP, NF1),
	// CNVI_RGI_DT
	PAD_CFG_NF(GPP_J4, NONE, DEEP, NF1),
	// CNVI_RGI_RSP
	PAD_CFG_NF(GPP_J5, UP_20K, DEEP, NF1),
	// CNVI_MFUART2_RXD
	PAD_CFG_NF(GPP_J6, NONE, DEEP, NF1),
	// CNVI_MFUART2_TXD
	PAD_CFG_NF(GPP_J7, NONE, DEEP, NF1),
	// GPIO4_GC6_NVDD_EN_R
	PAD_CFG_GPI(GPP_J8, NONE, PLTRST),
	// NC
	PAD_CFG_GPI(GPP_J9, NONE, DEEP),
	// DGPU_OVRM
	PAD_CFG_GPO(GPP_K0, 0, DEEP),
	// NC
	PAD_CFG_GPI(GPP_K1, NONE, DEEP),
	// DGPU_PWRGD_R
	PAD_CFG_GPI(GPP_K2, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_K3, NONE, DEEP),
	// Test Point
	PAD_CFG_GPI(GPP_K4, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_K5, NONE, DEEP),
	// EDP_HPD
	PAD_CFG_NF(GPP_K6, NONE, DEEP, NF1),
	// HDMI_HPD
	PAD_CFG_NF(GPP_K7, NONE, DEEP, NF1),
	// VCCIN_AUX_VID0
	PAD_CFG_NF(GPP_K8, NONE, DEEP, NF1),
	// VCCIN_AUX_VID1
	PAD_CFG_NF(GPP_K9, NONE, DEEP, NF1),
	// DGPU_MDP_HPD
	_PAD_CFG_STRUCT(GPP_K10, 0x46880100, 0x0000),
	// GC6_FB_EN_PCH
	PAD_CFG_GPI(GPP_K11, DN_20K, DEEP),
	// HDA_BITCLK
	PAD_CFG_NF(GPP_R0, NONE, DEEP, NF1),
	// HDA_SYNC
	PAD_CFG_NF(GPP_R1, NATIVE, DEEP, NF1),
	// HDA_SDOUT
	PAD_CFG_NF(GPP_R2, NATIVE, DEEP, NF1),
	// HDA_SDIN0
	PAD_CFG_NF(GPP_R3, NATIVE, DEEP, NF1),
	// AZ_RST#_R / ME_WE
	PAD_CFG_NF(GPP_R4, NONE, DEEP, NF1),
	// Test Point
	PAD_CFG_GPI(GPP_R5, NONE, DEEP),
	// Test Point
	PAD_CFG_GPI(GPP_R6, NONE, DEEP),
	// 100k pull-down
	PAD_CFG_GPI(GPP_R7, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_R8, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_R9, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_R10, NONE, DEEP),
	// ISH_GP_6_R
	PAD_CFG_GPI(GPP_R11, NONE, DEEP),
	// TP_ATTN#
	PAD_CFG_GPI_INT(GPP_R12, NONE, PLTRST, LEVEL),
	// NC
	PAD_CFG_GPI(GPP_R13, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_R14, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_R15, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_R16, NONE, DEEP),
	// 3G_CONFIG2
	PAD_CFG_GPI(GPP_R17, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_R18, NONE, DEEP),
	// DGPU_PWM_SELECT#
	PAD_CFG_GPI(GPP_R19, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_S0, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_S1, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_S2, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_S3, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_S4, NONE, DEEP),
	// NC
	PAD_CFG_GPI(GPP_S5, NONE, DEEP),
	// DMIC_CLK_PCH
	PAD_CFG_GPI(GPP_S6, NONE, DEEP),
	// DMIC_DAT_PCH
	PAD_CFG_GPI(GPP_S7, NONE, DEEP),
};

#endif

#endif
