/* SPDX-License-Identifier: GPL-2.0-only */

#include <mainboard/gpio.h>
#include <soc/gpio.h>

static const struct pad_config gpio_table[] = {
	PAD_NC(GPD0, NONE), // PM_BATLOW#
	PAD_CFG_NF(GPD1, NATIVE, DEEP, NF1), // AC_PRESENT
	PAD_CFG_GPI(GPD2, NATIVE, PWROK), // LAN_WAKEUP#
	PAD_CFG_NF(GPD3, UP_20K, DEEP, NF1), // PWR_BTN#
	PAD_CFG_NF(GPD4, NONE, DEEP, NF1), // SUSB#_PCH
	PAD_CFG_NF(GPD5, NONE, DEEP, NF1), // SUBC#_PCH
	PAD_NC(GPD6, NONE), // SLP_A#
	PAD_CFG_GPI(GPD7, NONE, PWROK), // GPD_7: crystal input
	PAD_CFG_NF(GPD8, NONE, DEEP, NF1), // PCH_SUSCLK
	PAD_NC(GPD9, NONE),
	PAD_NC(GPD10, NONE),
	PAD_NC(GPD11, NONE),

	PAD_CFG_NF(GPP_A0, NONE, DEEP, NF1), // SB_KBCRST#
	PAD_CFG_NF(GPP_A1, NONE, DEEP, NF1), // LPC_ADC0
	PAD_CFG_NF(GPP_A2, NONE, DEEP, NF1), // LPC_ADC1
	PAD_CFG_NF(GPP_A3, NONE, DEEP, NF1), // LPC_ADC2
	PAD_CFG_NF(GPP_A4, NONE, DEEP, NF1), // LPC_ADC3
	PAD_CFG_NF(GPP_A5, NONE, DEEP, NF1), // LPC_FRAME#
	PAD_CFG_NF(GPP_A6, NONE, DEEP, NF1), // SERIRQ
	PAD_NC(GPP_A7, NONE), // LPC_PIRQA#
	PAD_CFG_NF(GPP_A8, NONE, DEEP, NF1), // PM_CLKRUN#
	PAD_CFG_NF(GPP_A9, NONE, DEEP, NF1), // PCLK_KBC
	PAD_CFG_NF(GPP_A10, NONE, DEEP, NF1), // PCLK_TPM
	PAD_NC(GPP_A11, NONE),
	PAD_NC(GPP_A12, NONE),
	PAD_NC(GPP_A13, NONE), // SUSWARN#
	PAD_NC(GPP_A14, NONE),
	PAD_NC(GPP_A15, NONE), // SUS_PWR_ACK#
	PAD_NC(GPP_A16, NONE),
	PAD_NC(GPP_A17, NONE),
	PAD_NC(GPP_A18, NONE),
	PAD_CFG_GPO(GPP_A19, 1, DEEP), // SB_BLON
	PAD_NC(GPP_A20, NONE),
	PAD_NC(GPP_A21, NONE),
	PAD_NC(GPP_A22, NONE),
	PAD_NC(GPP_A23, NONE),

	PAD_NC(GPP_B0, NONE),
	PAD_NC(GPP_B1, NONE),
	PAD_NC(GPP_B2, NONE),
	PAD_CFG_GPO(GPP_B3, 1, DEEP), // BT_EN
	PAD_CFG_GPO(GPP_B4, 1, DEEP), // WLAN_EN
	PAD_NC(GPP_B5, NONE),
	PAD_NC(GPP_B6, NONE),
	PAD_NC(GPP_B7, NONE),
	PAD_NC(GPP_B8, NONE),
	PAD_NC(GPP_B9, NONE),
	PAD_NC(GPP_B10, NONE),
	PAD_NC(GPP_B11, NONE),
	PAD_NC(GPP_B12, NONE),
	PAD_CFG_NF(GPP_B13, NONE, DEEP, NF1), // PLT_RST#
	PAD_CFG_NF(GPP_B14, NONE, DEEP, NF1), // PCH_SPKR
	PAD_NC(GPP_B15, NONE),
	PAD_NC(GPP_B16, NONE),
	PAD_NC(GPP_B17, NONE),
	PAD_NC(GPP_B18, NONE), // LPSS_GSPI0_MOSI
	PAD_NC(GPP_B19, NONE),
	_PAD_CFG_STRUCT(GPP_B20, 0x42040100, 0x0000), // SMI#
	PAD_NC(GPP_B21, NONE),
	PAD_CFG_GPI(GPP_B22, NONE, DEEP), // LPSS_GSPI1_MOSI: LPC boot strap
	_PAD_CFG_STRUCT(GPP_B23, 0x80880100, 0x3000), // SCI#

	PAD_CFG_NF(GPP_C0, NONE, DEEP, NF1), // SMB_CLK / SMC_ASM1562
	PAD_CFG_NF(GPP_C1, NONE, DEEP, NF1), // SMB_DATA / SMD_ASM1562
	PAD_CFG_GPI(GPP_C2, NONE, DEEP), // GPP_C2_BT_UART_WAKE_N
	PAD_NC(GPP_C3, NONE),
	PAD_NC(GPP_C4, NONE),
	PAD_CFG_GPO(GPP_C5, 1, DEEP), // M.2_WLAN_WIFI_WAKE_N
	PAD_NC(GPP_C6, NONE), // SMC_CPU_THERM
	PAD_NC(GPP_C7, NONE), // SMD_CPU_THERM
	PAD_CFG_GPI(GPP_C8, NONE, DEEP), // TPM_DET
	PAD_CFG_GPI(GPP_C9, DN_20K, DEEP), // BOARD_ID1
	PAD_CFG_GPI(GPP_C10, DN_20K, DEEP), // BOARD_ID2
	PAD_CFG_GPI(GPP_C11, DN_20K, DEEP), // BOARD_ID3
	PAD_CFG_GPI(GPP_C12, NONE, DEEP), // GC6_FB_EN_PCH
	PAD_CFG_GPO(GPP_C13, 1, DEEP), // GPU_EVENT#
	PAD_CFG_GPO(GPP_C14, 1, DEEP), // M.2_PLT_RST_CNTRL1_N
	PAD_NC(GPP_C15, NONE),
	PAD_CFG_NF(GPP_C16, NONE, PLTRST, NF1), // I2C_SDA_TP
	PAD_CFG_NF(GPP_C17, NONE, PLTRST, NF1), // I2C_SCL_TP
	PAD_NC(GPP_C18, NONE),
	PAD_NC(GPP_C19, NONE),
	PAD_CFG_NF(GPP_C20, UP_20K, DEEP, NF1), // UART2_RXD
	PAD_CFG_NF(GPP_C21, UP_20K, DEEP, NF1), // UART2_TXD
	PAD_NC(GPP_C22, NONE), // UART2_RTS#
	PAD_NC(GPP_C23, NONE), // UART2_CTS#

	PAD_NC(GPP_D0, NONE),
	PAD_NC(GPP_D1, NONE),
	PAD_NC(GPP_D2, NONE),
	PAD_NC(GPP_D3, NONE),
	PAD_NC(GPP_D4, NONE),
	PAD_CFG_NF(GPP_D5, NONE, DEEP, NF3), // M.2_BT_PCMFRM_CRF_RST_N
	PAD_CFG_NF(GPP_D6, NONE, DEEP, NF3), // M.2_BT_PCMOUT_CLKREQ0
	PAD_CFG_GPI(GPP_D7, NONE, DEEP), // M.2_BT_PCMIN
	PAD_CFG_GPO(GPP_D8, 1, DEEP), // M.2_BT_PCMCLK
	PAD_NC(GPP_D9, NONE),
	PAD_NC(GPP_D10, NONE),
	PAD_NC(GPP_D11, NONE),
	PAD_NC(GPP_D12, NONE),
	PAD_NC(GPP_D13, NONE),
	PAD_NC(GPP_D14, NONE),
	PAD_NC(GPP_D15, NONE),
	PAD_NC(GPP_D16, NONE),
	PAD_NC(GPP_D17, NONE),
	PAD_NC(GPP_D18, NONE),
	PAD_NC(GPP_D19, NONE),
	PAD_NC(GPP_D20, NONE),
	PAD_NC(GPP_D21, NONE),
	PAD_NC(GPP_D22, NONE),
	PAD_NC(GPP_D23, NONE),

	PAD_NC(GPP_E0, NONE),
	PAD_CFG_NF(GPP_E1, NONE, DEEP, NF1), // M.2_SSD1_PEDET
	PAD_NC(GPP_E2, NONE),
	PAD_NC(GPP_E3, NONE),
	PAD_NC(GPP_E4, NONE),
	PAD_CFG_GPO(GPP_E5, 1, DEEP), // M2_P0_SATA_DEVSLP
	PAD_NC(GPP_E6, NONE),
	PAD_NC(GPP_E7, NONE),
	PAD_CFG_NF(GPP_E8, NONE, DEEP, NF1), // PCH_SATAHDD_LED#
	PAD_NC(GPP_E9, NONE), // USB_OC0#
	PAD_NC(GPP_E10, NONE), // USB_OC1#
	PAD_NC(GPP_E11, NONE), // USB_OC2#
	PAD_NC(GPP_E12, NONE), // USB_OC3#

	PAD_NC(GPP_F0, NONE),
	PAD_NC(GPP_F1, NONE), // SATAGP4
	PAD_NC(GPP_F2, NONE),
	PAD_NC(GPP_F3, NONE),
	PAD_NC(GPP_F4, NONE),
	PAD_CFG_GPI(GPP_F5, NONE, DEEP), // KBLED_DET
	PAD_CFG_NF(GPP_F6, NONE, DEEP, NF1), // LIGHT_KB_DET#
	PAD_NC(GPP_F7, NONE), // MHDD_SATA_DEVSLP
	PAD_NC(GPP_F8, NONE),
	PAD_NC(GPP_F9, NONE),
	PAD_CFG_GPI(GPP_F10, NONE, DEEP), // BIOS_REC: BIOS recovery enable strap
	PAD_CFG_GPI(GPP_F11, NONE, DEEP), // GPP_F11: reserved strap
	PAD_NC(GPP_F12, NONE),
	PAD_CFG_GPI(GPP_F13, NONE, DEEP), // GP39_GFX_CRB_DETECT: GFX select table strap
	PAD_CFG_GPI(GPP_F14, NONE, DEEP), // H_SKTOCC_N
	PAD_NC(GPP_F15, NONE), // USB_OC4#
	PAD_NC(GPP_F16, NONE),
	PAD_NC(GPP_F17, NONE),
	PAD_NC(GPP_F18, NONE), // USB_OC7#
	PAD_CFG_NF(GPP_F19, NONE, DEEP, NF1), // NB_ENAVDD
	PAD_CFG_NF(GPP_F20, NONE, DEEP, NF1), // BLON
	PAD_CFG_NF(GPP_F21, NONE, DEEP, NF1), // EDP_BRIGHTNESS
	PAD_CFG_GPO(GPP_F22, 0, DEEP), // DGPU_RST#_PCH
	PAD_CFG_GPO(GPP_F23, 0, DEEP), // DGPU_PWR_EN

	PAD_NC(GPP_G0, NONE),
	PAD_CFG_GPI(GPP_G1, NONE, DEEP), // CNVI_WIGIG_DET#
	PAD_NC(GPP_G2, NONE),
	PAD_NC(GPP_G3, NONE),
	PAD_NC(GPP_G4, NONE),
	PAD_NC(GPP_G5, NONE),
	_PAD_CFG_STRUCT(GPP_G6, 0x40880100, 0x0000), // SWI#
	PAD_NC(GPP_G7, NONE),

	PAD_NC(GPP_H0, NONE),
	PAD_NC(GPP_H1, NONE),
	PAD_CFG_NF(GPP_H2, NONE, DEEP, NF1), // CLK_REQ9_PEG#
	PAD_NC(GPP_H3, NONE),
	PAD_NC(GPP_H4, NONE),
	PAD_NC(GPP_H5, NONE),
	PAD_CFG_NF(GPP_H6, NONE, DEEP, NF1), // CLK_REQ13_SSD1#
	PAD_CFG_NF(GPP_H7, NONE, DEEP, NF1), // GPP_H_0_SRCCLKREQB_14
	PAD_CFG_NF(GPP_H8, NONE, DEEP, NF1), // CLK_REQ15_LAN#
	PAD_CFG_NF(GPP_H9, NONE, DEEP, NF1), // CLK_REQ16_CARD#
	PAD_NC(GPP_H10, NONE),
	PAD_NC(GPP_H11, NONE),
	PAD_NC(GPP_H12, NONE), // GPP_H_12: ESPI FLASH SHARING MODE
	PAD_NC(GPP_H13, NONE),
	PAD_NC(GPP_H14, NONE),
	PAD_NC(GPP_H15, NONE), // GPP_H15: reserved strap
	PAD_NC(GPP_H16, NONE),
	PAD_NC(GPP_H17, NONE),
	PAD_NC(GPP_H18, NONE),
	PAD_NC(GPP_H19, NONE),
	PAD_NC(GPP_H20, NONE),
	PAD_NC(GPP_H21, NONE), // GPP_H21
	PAD_NC(GPP_H22, NONE),
	PAD_NC(GPP_H23, NONE),

	_PAD_CFG_STRUCT(GPP_I0, 0x46880100, 0x0000), // G_DP_DHPD_F
	_PAD_CFG_STRUCT(GPP_I1, 0x46880100, 0x0000), // HDMI_HPD
	_PAD_CFG_STRUCT(GPP_I2, 0x46880100, 0x0000), // G_DP_DHPD_E
	PAD_NC(GPP_I3, NONE),
	PAD_CFG_NF(GPP_I4, NONE, DEEP, NF1), // EDP_HPD
	PAD_NC(GPP_I5, NONE),
	PAD_NC(GPP_I6, NONE),
	PAD_NC(GPP_I7, NONE),
	PAD_NC(GPP_I8, NONE),
	PAD_NC(GPP_I9, NONE),
	PAD_NC(GPP_I10, NONE),
	PAD_CFG_GPI(GPP_I11, NONE, DEEP), // H_SKTOCC_N
	PAD_NC(GPP_I12, NONE),
	PAD_NC(GPP_I13, NONE),
	PAD_NC(GPP_I14, NONE),

	PAD_CFG_NF(GPP_J0, NONE, DEEP, NF1), // CNVI_GNSS_PA_BLANKING
	_PAD_CFG_STRUCT(GPP_J1, 0x44000a01, 0x0000), // GPP_J1
	PAD_NC(GPP_J2, NONE),
	PAD_NC(GPP_J3, NONE),
	PAD_CFG_NF(GPP_J4, NONE, DEEP, NF1), // M.2_CNV_BRI_DT
	PAD_CFG_NF(GPP_J5, NONE, DEEP, NF1), // M.2_CNV_BRI_RSP
	PAD_CFG_NF(GPP_J6, NONE, DEEP, NF1), // M.2_CNV_RGI_DT
	PAD_CFG_NF(GPP_J7, NONE, DEEP, NF1), // M.2_CNV_RGI_RSP
	PAD_NC(GPP_J8, NONE),
	PAD_CFG_GPI(GPP_J9, NONE, DEEP), // CNVI_MFUART2_TXD: VCCPSPI voltage select
	PAD_NC(GPP_J10, NONE),
	PAD_NC(GPP_J11, NONE),

	PAD_NC(GPP_K0, NONE),
	PAD_NC(GPP_K1, NONE),
	PAD_NC(GPP_K2, NONE),
	PAD_NC(GPP_K3, NONE),
	PAD_NC(GPP_K4, NONE),
	PAD_NC(GPP_K5, NONE),
	PAD_NC(GPP_K6, NONE),
	PAD_NC(GPP_K7, NONE),
	PAD_CFG_GPO(GPP_K8, 1, DEEP), // SATA_M2_PWR_EN
	PAD_NC(GPP_K9, NONE),
	PAD_NC(GPP_K10, NONE),
	PAD_NC(GPP_K11, NONE),
	PAD_NC(GPP_K12, NONE),
	PAD_NC(GPP_K13, NONE),
	PAD_CFG_GPI(GPP_K14, NONE, DEEP), // GPP_K_14_GSXDIN: DMI AC coupling full voltage
	PAD_NC(GPP_K15, NONE),
	PAD_NC(GPP_K16, NONE),
	PAD_NC(GPP_K17, NONE),
	PAD_NC(GPP_K18, NONE),
	PAD_NC(GPP_K19, NONE),
	PAD_NC(GPP_K20, NONE),
	PAD_NC(GPP_K21, NONE),
	PAD_NC(GPP_K22, NONE),
	PAD_NC(GPP_K23, NONE),
};

void mainboard_configure_gpios(void)
{
	gpio_configure_pads(gpio_table, ARRAY_SIZE(gpio_table));
}
